### ISSUE TITLE
Question/Research: What happened if an app try to register CC when a library already has and vice-versa

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#102]
The context of this question is:

As JSAPI will have a CC dependency, what happened if:
- JASPI lazily register the CC but the app has already register CC?
- JSAPI has dependency on version X but the app has dependency on version Y?

The more low level questions are:
- How backward/forward compatibility or breaking changes will be handled? We need a clear path forward for these scenarios as we know they will occur
- Do we know what happened exactly if CC components already got registered with version X and a new registration is requested for version Y? Is Y replacing X? Do we get an error message?

**Comment by jcfranco** [comment]
Sorry for the unacceptably long delay on this. Here are my thoughts on this: 

> How backward/forward compatibility or breaking changes will be handled? We need a clear path forward for these scenarios as we know they will occur

Semantic versioning should help here since it gives a clear picture about the changes coming from an updated package.

> Do we know what happened exactly if CC components already got registered with version X and a new registration is requested for version Y? Is Y replacing X? Do we get an error message?

The browser should throw a [`NotSupportedError` if a duplicate custom element is registered](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Exceptions), but the following pen seems to throw a Stencil-related error: https://codepen.io/jcfranco-the-scripter/pen/XWbXoOx?editors=1000

> JASPI lazily register the CC but the app has already register CC?
> JSAPI has dependency on version X but the app has dependency on version Y?

I think for flexibility, we'll want to leave dependency setup to consumers. This will be easier to manage once all component libs are strictly following semantic versioning. This should help users in making the decision to possibly switch to an updated yet compatible version.

**Comment by macandcheese** [comment]
@Esri/calcite-components does this need more discussion or can it be closed?

**Comment by ffaubry** [comment]
I will close and reopen if necessary.
