### ISSUE TITLE
Enhancement: render calcite-modal without header

### ISSUE THREAD

**Issue by nathan-barrett** [Esri/calcite-components#1034]
### Description
This is sort of a combination `calcite-modal` combination `calcite-alert` - I'm basically looking for a modal that can render *without* a header and have a close button similar to the `calcite-alert` or a `calcite-alert` that can render with a footer. In the image below, that error overlay can render with buttons in the footer, and we would like to be able to use a calcite component in the future. 
#### Which Component
Either `calcite-modal` or `calcite-alert`
#### Example Use Case
![In home app](https://user-images.githubusercontent.com/30009669/94213523-d96e1180-fe8b-11ea-8bc7-9dca3d278024.png)

**Comment by macandcheese** [comment]
Basically for a confirmation of dismissal while in a modal?

@bstifle we've kind of talked about this before, Maybe looking less like a Calcite alert since that's a little "stacky" on top of a modal, but some kind of modal takeover that prevents interaction with modal content and allows for title, "subtitle" copy, and then probably a "confirm" and "cancel" area for buttons. 

Would that work @nathan-barrett ?

**Comment by nathan-barrett** [comment]
@macandcheese, yeah you have it 100% right. Thanks!

**Comment by nathan-barrett** [comment]
I think that this and the other enhancement i opened could be done easily together - https://github.com/Esri/calcite-components/issues/1033

**Comment by bstifle** [comment]
Here's the design proposed for this. 

- slot for an icon and color (32px calcite-ui)
- Slots for header and body
- And slots for 2-3 buttons
- Disable the X close button up top.
- rgba(255, 255, 255, 0.95) scrim over content and footer area

![1](https://user-images.githubusercontent.com/14083530/94303363-4b4d6600-ff33-11ea-9175-0325ac9b9ae6.png)
![2](https://user-images.githubusercontent.com/14083530/94303373-4ee0ed00-ff33-11ea-8fe2-2b9bad4d8198.png)

**Comment by julio8a** [comment]
Is this issue still valid?
