### ISSUE TITLE
New Component: Datalist

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1143]
_placeholder issue for 1.0.0 work_ cc @macandcheese

**Comment by macandcheese** [comment]
Datalist should be able to use the majority of the work from `calcite-select`, since the child items are options: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

`optgroup` is not supported: https://github.com/w3c/html/issues/932

This will allow typeahead filtering of options, and we can hopefully leverage our input component (perhaps we will need to position a trailing caret to indicate dropdown).

**Comment by macandcheese** [comment]
Still valid.

**Comment by macandcheese** [comment]
Valid?
