### ISSUE TITLE
Enhancement: Add RTL support for tile-select

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1230]
### Description

Tile select needs to support `dir="rtl"`:

<img width="1547" alt="Screen Shot 2020-11-05 at 11 08 36 AM" src="https://user-images.githubusercontent.com/4733155/98285605-a4a7ac80-1f57-11eb-9554-a11e60055cc3.png">

~We should also change the nomenclature for "show-input" from "left/right" to "start/end"~ (this is already implemented - Cari)

**Comment by caripizza** [comment]
Adding an update that Tile Select's rtl UI appears properly mirrored on page render. It's just using default browser behavior when text direction is rtl. In pr #2129 I added RTL stories to all Tile components which shows the UIs on render:

![image](https://user-images.githubusercontent.com/42423180/119165596-821c4300-ba12-11eb-9148-ce018ebd67c3.png)
![image](https://user-images.githubusercontent.com/42423180/119165641-906a5f00-ba12-11eb-91d0-1b08e43a38ca.png)
![image](https://user-images.githubusercontent.com/42423180/119165659-952f1300-ba12-11eb-99fc-dcb3c433a805.png)

As a part of #2108, Franco and I are removing the rtl commonTests I had added, and instead focusing on rtl stories for Screener.

Marking this one verified, since the RTL stories now exist on master.
