### ISSUE TITLE
Bug: Rating doesn't respond to clicks on wrapping calcite-label

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1294]
### Summary
I believe after this PR: https://github.com/Esri/calcite-components/pull/1264 - clicking on a wrapping calcite-label around a rating will no longer focus a rating item.

### Actual Behavior
![Screencast 2020-11-23 at 10 39 27 AM (1)](https://user-images.githubusercontent.com/4733155/100001580-385ee280-2d78-11eb-819f-efabeadac7ee.gif)
### Expected Behavior

Clicking on a wrapping calcite-label will successfully focus a rating item.

**Comment by driskull** [comment]
@macandcheese we can get this to work by storing the `input` element as a variable and using that to focus it instead of querying `this.el`. The issue is that it can't query into the shadowDOM.

However, there is still some weird focus inconsistencies because when tabbing forward vs backwards either the first or last star is focused.

As a user, I would expect the whole thing to be focused and not just the last or first star right?

**Comment by macandcheese** [comment]
Yeah I think we can update the setfocus method now that it’s basically a hidden radio input under the hood. 

Previously it was just a set of rendered elements so we were just focusing either the first if no user value was set, or the user set value if one had been.

**Comment by bstifle** [comment]
verified is working
