### ISSUE TITLE
calcite-button is not tabbable when appearance="inline"

### ISSUE THREAD

**Issue by vcolavin** [Esri/calcite-components#132]
## To reproduce
```tsx
<calcite-button appearance='inline'>hello friend</calcite-button>
```

## Expected result
You should be able to tab to this inline button (which really renders as an anchor tag).

## Actual result
You can't tab to it ;(

## Workaround
Adding an `href` makes it tabbable:

```tsx
<calcite-button 
  appearance='inline'
  href='literally-anything'
>
  hello friend
</calcite-button>
```

I guess the browser notices an anchor tag with no href and takes it out of the tab index!

## Suggested fix
I think that rendering a what is semantically "button" as an anchor might be a bit of an accessibility anti-pattern. Is there any way for it to still be a "real" button under the hood?

Otherwise we could set a default href of `#`, which I think is harmless.

**Comment by macandcheese** [comment]
Nice find. The reason for rendering "inline" appearance `<calcite-button>` as an `<a>` is that it is then style-able as a wrapping bit of text that can be positioned "inline" and, most importantly, wrap multi-lines in text blocks. I was stumped at how to achieve the same styling with a `<button>`, but you are right in that's it's kind of hacky! I will do some digging to see if I can make it work. All other `<calcite-buttons>` that render as `<a>` due to the presence of a "href" I think should be tabbable and semantically correct.

**Comment by vcolavin** [comment]
I figured it was something like that...

It totally makes sense to keep the ones with an `href` as an anchor! But for the `appearance="inline"` buttons... does `display: inline` do the trick?

**Comment by macandcheese** [comment]
Unfortunately `buttons` can't be styled in that fashion due to some weird untraceable default browser styling. I think adding a "#" as href might be a relatively safe way to allow this.

**Comment by vcolavin** [comment]
😞 that's fair. Thank you for your diligence!

In that case, I think we should make the `a` have `role="button"` when appropriate. Currently, when appearance is inline it has `role="link"`.

**Comment by macandcheese** [comment]
Just set tabindex to 0 on all tags works: https://github.com/Esri/calcite-components/pull/150
