### ISSUE TITLE
Bug: calcite-alert accessible test fails color guidelines

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1334]
### Summary

Bug: calcite-alert accessible test fails color guidelines

### Actual Behavior

Bug: calcite-alert accessible test fails color guidelines

### Expected Behavior

a11y test passes color guidelines

### Reproduction Steps

1.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/1327/files#diff-1ec454f16fab1bf107bd7f8844ff923fbf024c2be81b961f56d40201f1d59056R13

https://github.com/Esri/calcite-components/pull/1327#issuecomment-736752919

**Comment by macandcheese** [comment]
I can't get it to fail locally.

I'd imagine it might be failing on Travis because it's still in the process of "animating in" - if you look at the rendered colors of the elements it indicates as failures, they don't match what's actually rendered... maybe the accessible helper could accept an optional timeout duration to pass to accommodate for animations (which we do in the alert tests for other items)

**Comment by driskull** [comment]
> maybe the accessible helper could accept an optional timeout duration to pass to accommodate for animations

Yeah we can do this.

**Comment by macandcheese** [comment]
@driskull this was never replicable locally, going to close. Feel free to re-open if it still fails occasionally but this is pretty old now.
