### ISSUE TITLE
Bug: calcite-checkbox focus outline is multiplied and persistent

### ISSUE THREAD

**Issue by crowjonah** [Esri/calcite-components#1566]
### Summary

In Safari (`Version 14.0.3 (15610.4.3.1.6, 15610)`), I have Preferences > Advanced > Accessibility > "Press Tab to highlight each item on a webpage" checked. Without this setting, `calcite-checkbox` elements are not tab accessible. While tabbing, focus outlines persist even when the element no longer has focus, and also appears to render oddly.

### Actual Behavior

GIF screen recordings from the Storybooks demo pages for `card` and `checkbox`.

![card checkbox safari tab focus](https://user-images.githubusercontent.com/1634397/108216158-26cf7180-7100-11eb-8588-38594ef392c8.gif)

![checkbox safari tab focus](https://user-images.githubusercontent.com/1634397/108216164-28009e80-7100-11eb-9d42-3d57033e817f.gif)

### Expected Behavior

Checkboxes should be tab-accessible, visually distinct when focused, and render normally when not focused.

**Comment by driskull** [comment]
@eriklharper @macandcheese Do you know why we have a `focused` property on this component? Shouldn't we have a setFocus method?

I think the issue may be related to the focused property. It watches for onFocus and then sets focused property which then calls focus again.

cc @jcfranco for API consistency.

**Comment by eriklharper** [comment]
The `focused` property is there so that the hidden `<input>`'s blur and focus methods can be responded to in order to update styling on the host UI.  This is so the keyboard can navigate normally to the hidden input and the `calcite-checkbox` styling will update appropriately.

**Comment by driskull** [comment]
@eriklharper I think we should separate the focus and the styling for this. The problem that it's setting styling but it is also setting the focus on the input. We should be doing that through a setFocus method to be consistent.

What if we called it `active` instead of `focused` and let focusing happen through setFocus?

The issue now is that the input already has event listeners for focus and blur that are setting `focused` but then there is a watcher that calls blur or focus. https://github.com/Esri/calcite-components/blob/master/src/components/calcite-checkbox/calcite-checkbox.tsx#L56-L63

So if the input is blurred, it calls blur again. If the input is focused, it calls focus() again.

**Comment by eriklharper** [comment]
Fixed by #1603
