### ISSUE TITLE
Component: calcite-button - would be nice to set the type to be "submit"

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#157]
We'd like to set the type of the button for calcite-button to be "submit" so we can leverage form validation

**Comment by macandcheese** [comment]
Good catch, going to work on this. 

Buttons by default are `type="submit"`, so the only passable options are `reset` or `button`.

The issue is that there's no way for the rendered child button in shadow DOM to communicate to the containing "non shadow DOM" form that an event occurred on the rendered child button. This is how Ionic / Stencil solves: https://github.com/ionic-team/ionic/blob/bf2953cf85c078b0fd567e51208eacd5dc9b87cd/core/src/components/button/button.tsx#L150 - but that doesn't seem to solve for the possibility of multiple submit buttons placed outside forms, so I'll try and solve for that as well.

**Comment by macandcheese** [comment]
Added in https://github.com/Esri/calcite-components/pull/158
