### ISSUE TITLE
Bug: calcite-input-date-picker issue with Arabic

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1880]
### Summary

This does not seem correctly formatted for Arabic.

![image](https://user-images.githubusercontent.com/44481292/113224006-4bf6ea00-923f-11eb-9e33-086e057a9ca1.png)

Hebrew is fine.

![image](https://user-images.githubusercontent.com/44481292/113224064-6f219980-923f-11eb-9eae-43ef9d063a9a.png)

### Reproduction Steps

1.

**Comment by driskull** [comment]
@AdelheidF this would be for Paul.

**Comment by paulcpederson** [comment]
@AdelheidF can you give more details, what locale string are you sending?

**Comment by AdelheidF** [comment]
![image](https://user-images.githubusercontent.com/44481292/113225584-da209f80-9242-11eb-98c1-4e8a51a2070e.png)

**Comment by AdelheidF** [comment]
I'm not sure if this is the case here, but when a string contains things like slashes, you can't build the fully formatted string in the code. We normally have to add the complete string with placeholders into the language file and the translators change it in a way so that the formatting is correct in the UI.

**Comment by paulcpederson** [comment]
Not there are bigger problems with the `input` part of this component. Previously this was one component and arabic rendered correctly, but looks like now it's wrong. If you open the calendar picker you'll see the right to left +correct arabic numerals, day names, month names, etc.

**Comment by driskull** [comment]
It might be fine after next is updated 🤷  :)

**Comment by AdelheidF** [comment]
Seems to work with next.139

![image](https://user-images.githubusercontent.com/44481292/113230440-d9d9d180-924d-11eb-8cb4-4243dbccc597.png)

**Comment by raje9276** [comment]
@AdelheidF @paulcpederson Why does the input (Text box) shows latin number but the Calendar control shows Indic numbers?

The right behavior should be Text box matching the calendar control 
Example: WPF Control
![image](https://user-images.githubusercontent.com/30269081/113247610-3b129c80-9270-11eb-9dbc-098899e1d189.png)

**Comment by paulcpederson** [comment]
I agree, but even the WPF control has mixed numbers, notice the year is in arabic...

**Comment by babakbolour** [comment]
@paulcpederson what Rajeev is pointing to is the 'date format' issue (should be <day>/<month>/<year>). Presentation of the digits itself (indic vs western)  is a diff story; but both acceptable at this time.

**Comment by caripizza** [comment]
@raje9276 @babakbolour can one of you please clarify why this issue was re-opened instead of creating a new issue based on your follow-up comments? If we don't have an actionable, clear description of the new "wrong" behavior here - based on our updated Bug issue template - then I can't prioritize this alongside our other issues.

**Comment by raje9276** [comment]
![image](https://user-images.githubusercontent.com/30269081/116766332-c81b5380-a9de-11eb-8646-ccd8eb854642.png) ![image](https://user-images.githubusercontent.com/30269081/116766361-ee40f380-a9de-11eb-98d5-8f58ddd621b1.png)

@caripizza the Calendar should display western numbers (latin) rather than Indic numbers. 
Do you want me to close this issue and open a new issue?

**Comment by caripizza** [comment]
@raje9276 yes please - thank you for your help.

**Comment by raje9276** [comment]
@AdelheidF Please go ahead and close this issue.

A related issue is created at https://github.com/Esri/calcite-components/issues/2095
