### ISSUE TITLE
Bug: setting the value of a `calcite-input` to `undefined` gives errors in the console

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#2002]
### Summary
Rendering `calcite-input` in stencil (could happen in other jsx/vdom) and setting the `value` property to undefined gives errors in the console.

![image](https://user-images.githubusercontent.com/52869490/115462888-0abf7d80-a1e0-11eb-8145-a2a5e58a3b0f.png)

**Comment by noahmulfinger** [comment]
I think I have the same issue in a slightly different context. When a form reset happens before a calcite-input is finished loading into the page, it throws the above error. I created a codepen for it: https://codepen.io/noahmulfinger/pen/yLgGJwj?editors=1010. Seems like it should get fixed by 4021b90, but if not I can open a separate issue.

**Comment by eriklharper** [comment]
Fixed by #2036
