### ISSUE TITLE
Bug: calcite-select - down arrow on wrong side in RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2147]
This worked correctly with beta.54. 
![image](https://user-images.githubusercontent.com/44481292/118189685-f2b1d700-b3f6-11eb-94bc-538b7b8f4255.png)

It no longer works correctly with next.190.
![image](https://user-images.githubusercontent.com/44481292/118189719-fcd3d580-b3f6-11eb-8569-5830c966f63b.png)

https://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0&locale=he
Open filter and add expression

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Noticed this too when calcite-select in rtl has calcite-option-group within it. Thanks for reporting this @AdelheidF. 

Just needs to use the rtl class selector to fix this (instead of the attribute):
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-select/calcite-select.scss#L94
```scss
.icon-container.calcite--rtl {
```

**Comment by caripizza** [comment]
Hi @AdelheidF this was installed in beta.56, and is ready for your verification.

**Comment by AdelheidF** [comment]
tested with beta.56, it's fine now.

![image](https://user-images.githubusercontent.com/44481292/121240841-a15b0300-c84f-11eb-941d-9f4e274ec18e.png)
