### ISSUE TITLE
Tooling: Set up Screener to test against demo pages

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2177]
## Summary 

With https://github.com/Esri/calcite-components/issues/2174, we'll want to include those pages into Screener's testing routine to improve testing of visual regressions.

We could use this as a first step towards https://github.com/Esri/calcite-components/issues/2019.

## Measure of Success 

Demo pages are included as part of the Screener screenshot test suite.

### Resources 

N/A

**Comment by driskull** [comment]
From the little research I've done it seems like we would need the CI to run our local build and serve the demos so that the screener-runner can access the local URL and begin running visual tests.

I'm not sure we we can use the built in stencil server or if we need to copy the files and use something else? If we can use the stencil server, we need to be able to hook into when it is ready and in a separate process start running the visual tests.

Maybe the screener team can help us here.

**Comment by eriklharper** [comment]
Here's the response I got back from Loyal that guides us through the steps to try to make this work:

> Hi Erik,

> Screener-runner is used under the hood of the screener-storybook module, so it should be able to do what you need.
> As you've run this locally, I'm assuming you used screener-runner's built-in tunnel option [github.com] - this can be used to > connect to a web server running in a CI build job as well.

> The process you've outlined at the end sounds like it should work:
> In your CI Build script, fire up your web server with demo pages. Let's assume this web server then becomes accessible in > > the CI job via http://localhost:3000 [localhost]
> Ensure your screener-runner config has the "tunnel" option set to host "localhost:3000"
> Then in your CI script run screener-runner using npm
> Hope that helps, thanks,

> Loyal

**Comment by driskull** [comment]
Yep that makes sense.

I guess the part I'm unsure of is if the web server can just be the stencil build with the `--serve` argument. If so, what are the hooks we need to listen for to be able to start running the screener-runner.

**Comment by eriklharper** [comment]
As I recall, this was a stumbling block I ran into as well.  I remember putting in a wait somewhere so that my local server was running properly before the runner started.

**Comment by driskull** [comment]
Just playing devils advocate here... 😈 

Storybook-screener solves these issues already and has a method to use the steps API in screener. Do we really want to move off of that? Would it be easier to just update the stories to have a single story that then does all the steps to toggle sizing, theme, rtl, etc and take screenshots after each step?

The nice thing about storybook-screener is its already a UI to present components and it has a way to navigate all the stories and take screenshots. We would have to come up with a way to find all the HTML files in the demo folder and go to each one, wait for it to load and then start the steps. It just seems like we're reinventing the wheel a little bit.

**Comment by julio8a** [comment]
We need automated integration in the demo pages as they show all the variations (props) in one place. This is very helpful for manual testing as we can see everything in one place and not have to click around to get props. 

It sounds like we need a bit more research on this and possible some help from Loyal and team?

**Comment by eriklharper** [comment]
> Would it be easier to just update the stories to have a single story that then does all the steps to toggle sizing, theme, rtl, etc and take screenshots after each step?

This is exactly the approach I employed at my last job.  Here's an example of a story I wrote that contains all the relevant permutations that Screener was able to capture and which we could manipulate to open dropdowns and such: https://arubanetworks.github.io/meridian-editor-frontend/?path=/story/singleselect--default

> The nice thing about storybook-screener is its already a UI to present components and it has a way to navigate all the stories and take screenshots. We would have to come up with a way to find all the HTML files in the demo folder and go to each one, wait for it to load and then start the steps. It just seems like we're reinventing the wheel a little bit.

It is definitely extra work to support both Storybook and Demo pages for sure.  I considered advocating for this exact idea early on, but realized that the stories served as developer documentation, not as a developer tool, but since we are moving away from using Storybook in that way and having the docs for our components be pushed to the Esri Developer site, then the case could be made that the storybook could be used for this purpose.

There are some caveats to this approach though.  If you look at that Storybook link I posted above, you'll notice there are no knobs or other addons in use.  We ditched those soon after we started using Screener Storybook because once the stories moved away from single instances of each component, knobs for changing props no longer made sense because you could see all the different prop permutations already and it would also beg the question of which instances of the component would respect the knob updates?

This trade-off was fine because these components were internal to the company and only used in a back office web application that administrators and other people internal to the organization used.  Esri's Calcite components are a public repository, so a much different kind of domain.

We should definitely involve as many voices as possible to consider these two options, but if we like the way Storybook is currently setup and feel like changing it to fit the needs of test automation does not trump the need to make it function like a developer site, then we should definitely go with the demo pages testing route.

A third option could be that we create a second storybook just for the purposes of screenshot testing.  I've never setup two different storybooks in a single repo before, but I imagine it would just be a matter of having two config files for each and setting up a new deployment pipeline, but that feels like it could be just as much work as getting screener-runner setup to run against our demo pages.

**Comment by eriklharper** [comment]
I've been busy with other things, but if we want to know sooner rather than later if the screener-runner approach will work smoothly, then I and others who would like to collaborate on this should start spending some time trying to set this up to see how far we can get with it.  I feel like I'll know a lot more about how things should go once I can see it working and evaluate the setup against just running this all from inside Storybook.

**Comment by driskull** [comment]
> since we are moving away from using Storybook in that way and having the docs for our components be pushed to the Esri Developer site, then the case could be made that the storybook could be used for this purpose.

This is what I was thinking too. We can just convert our storybook to act as a visual testing tool.

> A third option could be that we create a second storybook just for the purposes of screenshot testing

Yes, this would work too. If we still want to have a storybook for public consumption.

What we gain from using storybook to do visual testing is the automation of starting up the server, navigating to each page and taking screenshots.

The way the non storybook demos are setup, they show more than one component at a time. This is great for manual testing but I'm not sure that it is the best for visual diff testing. Ideally, the screenshot only shows the one component that is being tested. It may not matter that much though as long as the screenshot focuses only on what is being tested.

**Comment by eriklharper** [comment]
> The way the non storybook demos are setup, they show more than one component at a time. This is great for manual testing but I'm not sure that it is the best for visual diff testing. Ideally, the screenshot only shows the one component that is being tested. It may not matter that much though as long as the screenshot focuses only on what is being tested.

I actually think that the more you can stuff on the page, the better because Screener charges on a per-screenshot basis.  It is actually more economical to put all you can on a single page, which reduces the total number of screenshots per run.  Screener is excellent at picking up even the slightest changes regardless of how many pixels it is looking at.

**Comment by driskull** [comment]
Hah that's one way to get around pricing :) Have a ton of components on a single page and every component is basically a step.

The potential pitfalls is that opening one component may cover another. Unless they are spread out enough. Just seems like potential for conflict.

**Comment by eriklharper** [comment]
> The potential pitfalls is that opening one component may cover another. Unless they are spread out enough. Just seems like potential for conflict. Like opening a block is going to push down the page, etc.

This shouldn't matter because when you start adding Steps that open up other pieces of UI, Screener will take both an initial screenshot and a second screenshot after the new interaction was applied.  It is actually a good thing to do this because then you would also be able to see potential visual conflicts that occur as a result of the step interactions, such as things going out of alignment in the document flow or a popup being obscured because of a z-index issue in another nearby component, for example.

**Comment by driskull** [comment]
I guess that part probably falls into the research category.

Correct me if I'm wrong, but screener just takes a screenshot at a specified resolution and no scrolling the page right? Looking at the demos, it seems a lot of them require scrolling to have full coverage.

**Comment by eriklharper** [comment]
> Correct me if I'm wrong, but screener just takes a screenshot at a specified resolution and no scrolling the page right? Looking at the demos, it seems a lot of them require scrolling to have full coverage.

Great question.  I don't actually know the answer to that, but I can assume that based on the resolution and how much content the page contains, that yes, there would potentially be clipping of content.

**Comment by jcfranco** [comment]
Closing this since we'll be [moving away from Screener](https://github.com/Esri/calcite-components/issues/4825) at a later point. This should also help us stick to a single, consistent way of doing screenshot tests.
