### ISSUE TITLE
Docs: remove `theme` attribute from demo html and stories, use classes

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2262]
### Description 
This is a follow on to #2189. Now that pr #2194 is in, and we are deprecating the usage of `theme="light"` and `theme="dark"` attributes for hooking into a theme, we need to update our resources:

1. remove theme attribute from demo html pages
2. remove theme attribute from component stories

Refactors should instead use the new `.calcite-theme-light` or `.calcite-theme-dark` classes for setting deliberate themes on components.

(Once we have these resources updated, we'll then add documentation on how to use the light/dark themes via the new classes.)

### Which Component
- All component demo html pages
- All component stories

### Resources 

cc @driskull

**Comment by driskull** [comment]
For the stories, how do we want to proceed? Do we want a knob for the theme class? Or do we just want each story to have another "dark" theme story?

**Comment by caripizza** [comment]
I vote actual dark theme story for Screener screenshot tests if we can (like the RTL ones)

**Comment by caripizza** [comment]
Do you think it'd be good to keep the existing theme knobs in place too?

**Comment by driskull** [comment]
I'm not sure about the knobs. We would have to use a class which is kind of an odd knob.

**Comment by driskull** [comment]
I'm wondering if we should just remove both knobs for `theme` and `dir` and just have something to automatically generate `dark` and `RTL` stories for every story we create? This would give screener better coverage and be more automatic so that we only have to create unique stories. It would have to automatically export a const for dark/RTL

What do you think @jcfranco?
