### ISSUE TITLE
Bug: input-enabled calcite-tree not removing items from selected

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#2437]
### Actual Behavior
Items are not removed from the selected array (returned from `calciteTreeSelect` -> `event.detail.selected`) once they have been unchecked.

### Expected Behavior
When `input-enabled` is true and items are unselected, the items should be removed from the array: event.detail.selected.

### Reproduction Steps or Sample
https://codepen.io/joeyHarig/pen/eYWmpbm?editors=1111

### Relevant Info

_Version_: latest

**Comment by jcfranco** [comment]
@joeyHarig I started looking into this and noticed that it works correctly if you press the shift key when clicking items. You can use this as a workaround in the meantime. Also, note that the selection mode should be `multi` and not `multiple`.

@paulcpederson Since users have an expectation of how checkboxes should behave, should we always toggle the value when clicking an input-enabled tree item regardless of whether the shift key was pressed or not?

https://codepen.io/jcfranco/pen/PompyrW?editors=1111 (based off the original test case)

**Comment by paulcpederson** [comment]
@jcfranco this is a bug. This worked fine in beta.58 https://codepen.io/paulcp/pen/mdmWQRW 

I'm not sure what changed but they should work like checkboxes.

**Comment by jcfranco** [comment]
Thanks for the info! The regression is probably related to my previous changes. It's worth noting that the event payload selection issue is present in beta.58 too. Will fix! 💪🏼 🛠️

**Comment by jcfranco** [comment]
Installed!

**Comment by jcfranco** [comment]
@joeyHarig Can you help verify once this gets deployed to `@next`? 🙇🏼‍♂️

**Comment by joeyHarig** [comment]
@jcfranco Just verified that the issue has been resolved.

**Comment by jcfranco** [comment]
Awesome, thanks!
