### ISSUE TITLE
refactor(Pick List): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2454]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related issues:
- #1547

Related prs:
- pr #1682
- pr #1684
- pr #1686

Design:
- Needs full refactor, see figma spacing
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A7816

6/24: Mike Stinson is working on this refactor - CP

**Comment by asangma** [comment]
A note on the future refactor using Calcite List.
As mentioned in the comment [here](https://github.com/Esri/calcite-components/pull/2502#issuecomment-883610499), refactoring the PickListItem to user ListItem will allow the dot or checkmark to become part of the main hit area and thus the hover area.

This is true. However, any action added will be to the left (in LTR) of that check or dot since the check or dot will be in the content area.

**Comment by julio8a** [comment]
verified on master, local build demo pages.
