### ISSUE TITLE
refactor(Tree): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2460]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related issues:
- #2080
- #2041
- #2082

Related prs:
- pr #1732

Design:
- Needs full refactor, see Figma
- Needs Small Medium and Large Scales, see Figma
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A21400

**Comment by julio8a** [comment]
Is this one considered installed and ready for verification?
I see there's a break out issue for selection updates: #2082

**Comment by caripizza** [comment]
@julio8a I'm not sure. Figma still shows "pipes" and selection-mode "checkbox" where it should show "lines" and "ancestors" selection-mode. Bryan updated the tree comps midway through development in order to accommodate the 2 additional selection-modes that weren't initially considered. The latest designs don't yet appear in the blue selection area in Figma yet, they appear to the right of it.

Should we close this issue once those designs are updated?

**Comment by julio8a** [comment]
If it's just design work in Figma, we shouldn't wait to close this issue. I'll be creating an issue in the UI kit project for design updates to Figma and tie the work done here.

**Comment by caripizza** [comment]
Sounds good @julio8a

**Comment by benelan** [comment]
@julio8a, LGTM but can I get a designer's eyes on this for verification?

**Comment by macandcheese** [comment]
LGTM @benelan

**Comment by benelan** [comment]
Thanks, verified and closing
