### ISSUE TITLE
[Epic] Drop legacy code

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2600]
When this project started, it had to support IE11 along with other browsers that did not support native web component APIs, so it needed code and build options to target all browsers. We are at a stage where we can officially remove any remaining legacy code.

### Plan of action

- [x] drop any utils or code that feature-detects custom element APIs (#2604)
  - this may take more than a sprint, but we can do a comprehensive initial sweep and remove anything we may have missed in future sprints. 
  - codemods could help automate some of these changes
  - This is **not crucial** 1.0.0 as we can make these changes without impacting users. 
- [x] disable any Stencil build extra flags to support legacy browsers (#2617)
  - This should land early in a sprint for testing 
  - This should **probably happen before 1.0.0** to catch potential regressions in the distributable (theoretically should not be likely)  
- [x] miscellaneous cleanup (#2671)

**Comment by driskull** [comment]
@jcfranco do we need to support these extras?

### dynamicImportShim

Dynamic import() shim. This is only needed for Edge 18 and below, and Firefox 67 and below. Defaults to false.

### safari10

Safari 10 supports ES modules with <script type="module">, however, it did not implement <script nomodule>. When set to true, the runtime will patch support for Safari 10 due to its lack of nomodule support. Defaults to false.

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/pull/2604#discussion_r675762038

**Comment by jcfranco** [comment]
Closing as verified! 

Any remaining legacy code can be removed in separate PRs.
