### ISSUE TITLE
Bug: calcite-slider histogram not taking host width into account

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2706]
### Actual Behavior

The slider histogram has a fixed width and is not placed correctly based on the slider width.

### Expected Behavior

The histogram should align with the data values regardless of the slider's size.

### Reproduction Steps or Sample

1. Open https://codepen.io/jcfranco/pen/jOmpMLR?editors=1000
2. Notice how the histograms of the 3 differently-sized sliders have identical widths.

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.60`

- [x] CDN
- [ ] NPM package

This is a regression from beta 59, possibly from https://github.com/Esri/calcite-components/commit/9dd3812dc0f1294163e46b2f608272e27f6fa0d5.

**Comment by caripizza** [comment]
I happened upon this issue while investigating #2457. It looks like this started happening in 1.0.0-next.236, after setting `shadow: true` in [calcite-graph.tsx](https://github.com/Esri/calcite-components/pull/2423/files#diff-a8e20ed09e8a382be826d7c02796c4d0f4eb642b59d466e2375b63cf02214967R9).

The [`svg` slider selector style override](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-slider/calcite-slider.scss#L352) is no longer applying due to it being unreachable in graph's shadow dom. 

Should [graph's svg width](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-graph/calcite-graph.tsx#L85) be `"100%"` instead, so it automatically stretches the width of the container it's nested inside?

Or, can we add a new optional prop like `matchHostWidth` to graph, so slider can pass it as a truthy prop to the component? (in graph we would do `width={!this.matchHostWidth ? width : "100%"}`)

**Comment by caripizza** [comment]
Related: #2948

**Comment by jcfranco** [comment]
Verified w/ repro case!
