### ISSUE TITLE
Bug: Panel UI regressions

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2957]
### Actual Behavior
Panel had some UI updates that may not have been full vetted.
* The [back-button scale](https://github.com/Esri/calcite-components/commit/c211b04c6df10ab3695a7581781c2a97e95984ef#diff-fdbe551fa08339a23b3f85cd7119b1d75fa4cc666cd4d36369a8ce37355397edR235) is now medium which puts it on the same hierarchical level as other actions that might be added.
* The [increased padding](https://github.com/Esri/calcite-components/commit/c211b04c6df10ab3695a7581781c2a97e95984ef#diff-b21f80b9fd202502f92995d56073caa7d05c12dd8c9ef8a3622115ea048e8d50R103-R104) in header seems unneeded and eats up a lot of vertical space. We need to be economical with our vertical spacing. We know there are plenty of downstream end-users with small displays

### Expected Behavior
Revert header padding.
Revert Action scale

### Reproduction Steps or Sample

1. See any shell demo app or the panel demo page.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@jcfranco Would like to handle this before V1.

@macandcheese Any feedback on this?

**Comment by macandcheese** [comment]
@asangma agreed re: both, let's move to small scale for the back button - the icon inside stays the same size and it just shrinks it horizontally. 

Re: heading - they are super large now, maybe we could in the future look to the heading text lockup to get more vertical real estate.

**Comment by julio8a** [comment]
@asangma, we can tackle in this sprint if 9.3 needs this update.

**Comment by asangma** [comment]
Yeah...let's make it happen.

**Comment by justinhough** [comment]
@asangma I have made the following adjustments. From the screenshot that is using the original code and the bottom panel is using the updates below. Let me know if these changes look about right from the issue and I can get this changes pushed into a PR for review.

To note we could also use the calcite-action medium since that doesn't affect the vertical space, but only makes the button wider. The vertical spacing is tied to the header content padding top and bottom.

- Vertical padding adjusted back to `py-4` -> https://github.com/Esri/calcite-components/commit/c211b04c6df10ab3695a7581781c2a97e95984ef#diff-b21f80b9fd202502f92995d56073caa7d05c12dd8c9ef8a3622115ea048e8d50R103
- Action scale reverted to `s` -> https://github.com/Esri/calcite-components/commit/c211b04c6df10ab3695a7581781c2a97e95984ef#diff-fdbe551fa08339a23b3f85cd7119b1d75fa4cc666cd4d36369a8ce37355397edR235

![CleanShot 2021-09-03 at 09 14 31](https://user-images.githubusercontent.com/9469422/132028480-6f15930d-db5f-4f3f-8575-792eefdbdd85.png)

**Comment by justinhough** [comment]
@asangma Have you had a chance to look at this?

**Comment by julio8a** [comment]
@macandcheese any thoughts on this? ^

**Comment by macandcheese** [comment]
I think the resolution after chatting with @asangma last week was to proceed with the "bottom" example above. We will perhaps be able to further address this in https://github.com/Esri/calcite-components/issues/2972.

**Comment by asangma** [comment]
Toight!
