### ISSUE TITLE
Enhancement: Improve behavior of calcite-shell `content-behind` when used with `detached` shell panel

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2966]
### Description
I'd like to surface an issue I've encountered when using a `detached` `calcite-shell-panel` in combination with the `content-behind` prop on `calcite-shell`

Consider a layout with a map in the center, a non-`detached` `calcite-shell-panel`, and a `detached` `shell-panel`:

![Screen Shot 2021-09-02 at 8 39 24 AM](https://user-images.githubusercontent.com/4733155/131874348-8919a779-66b8-419e-bf74-89fd2c4a938e.png)

In order for the above to work (currently), I need to manually add a margin-left to the map container that equals the width of the non-`detached` shell panel on the left. Without this, the map extent is actually placed behind the panel:

![Screen Shot 2021-09-02 at 8 42 27 AM](https://user-images.githubusercontent.com/4733155/131874899-1abc8751-3516-4b66-848f-98084d63ea1d.png)

### Acceptance Criteria 

When `content-behind` is used, the center area should be restricted to the space behind `detached` shell panels only - ie, a user should not have to manually pad or place content in the center to avoid it being placed behind a non-`detached` shell panel.

### Relevant Info 
Honestly, I'd also expect `detached` to float above the content, even without `content-behind`, rather than just be "detached" within a shell panel swimlane - although related, that's slightly out of scope:

![Screen Shot 2021-09-02 at 8 41 57 AM](https://user-images.githubusercontent.com/4733155/131874880-aea7c860-8e68-4fc1-bbea-671f8786c9d9.png)

#### Which Component
 Shell / Shell Panel

cc @asangma let me know if the above needs to be clarified or if I'm missing a configuration option that does this already.

**Comment by asangma** [comment]
Admittedly, it's confusing. Here's the explanation. Note that I'm open to rethinking this.

`content-behind` is meant to work with a mapview's [view-padding](https://developers.arcgis.com/javascript/latest/sample-code/view-padding/) so that the view ui (container that holds the on-map widgets) can update without affecting the position of the map.

Not moving the map as panels open/close has historically been one of the requirements of the Map Viewer.

The expectation is that the app developer will update the view-padding in concert with the panels opening and closing.

As it is now, Shell defaults to `content-behind="false"` and the content in the default slot behaves as a center column and responds as such.

As far as `detached`, indeed it does need to work with `content-behind`. This is useful in Map Viewer but definitely confusing in general.

**Comment by macandcheese** [comment]
> `content-behind` is meant to work with a mapview's view-padding so that the view ui (container that holds the on-map widgets) can update without affecting the position of the map.

This will only work if the map itself is the only content, correct? If I put my map inside a calcite-panel (so I can have access to set a heading, and slot actions above the map), this approach doesn't work and I still need to set margin to move the center panel out from behind the shell-panel... 

an example:
![Screen Shot 2021-09-10 at 11 12 12 AM](https://user-images.githubusercontent.com/4733155/132898736-5a25a118-d43b-4a00-9e92-2718fdb463c5.png)

> The expectation is that the app developer will update the view-padding in concert with the panels opening and closing.

The variable-width of the shell-panels means users will need to listen for resizing, etc., to set a margin-left equal to that of the panel width, unless they constrain those.

**Comment by macandcheese** [comment]
Bumping this - still need to support a "non-detached" `shell-panel` on the left with a `detached` on the right.

**Comment by geospatialem** [comment]
Will work through the updated layout-based components, closing but can reopen at a later time.
