### ISSUE TITLE
Bug: calcite-input type:number allows multiple dashes

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3053]
https://developers.arcgis.com/calcite-design-system/components/input/
![image](https://user-images.githubusercontent.com/44481292/133652330-df000f96-f1e0-49d2-8fee-ab9a0e8a170c.png)

or 5-5-5-5

### Reproduction Steps and Sample

_Sample_:

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
As mentioned, this issue is reproducible in the doc so the request for additional information is not applicable, thanks!

**Comment by AdelheidF** [comment]
Could we please give this issue a higher priority? We get bug reports logged about it.

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/BawrLPz. Input is not restricted, but the value is properly parsed.

**Comment by AdelheidF** [comment]
I don't think it's fixed if it still allows users to enter values like '5-----'

**Comment by benelan** [comment]
We decided to not strict the input, but rather parse the value correctly. So even though it displays `5-----` , the value is `5`. Typing another five will remove the invalid dashes and it becomes `55`.

**Comment by AdelheidF** [comment]
Ok, so you do automatically undo user's characters if the user enters the second 5. Why not do it right away?

**Comment by benelan** [comment]
The native number input allows you to type the two hyphens and keeps them there. This is because `-5e-5` is a valid number. However with the native input you can also type `5-55-5`. And it doesn't parse out invalid hyphens. Would you restricting the number of dashes to two like native does be sufficient?

**Comment by eriklharper** [comment]
The native number input allows you to type up to 2 hyphens in the input so as to accommodate values like `-5e-5`.  We can't restrict the user from typing a hyphen at the end of the value because it would prevent them from being able to enter a value like the one above.  We can set this up so that it restricts the input to a maximum of 2 hyphens.

**Comment by AdelheidF** [comment]
Idea from Paul B. : it should fix itself when it looses focus

So we kind of expect users to type something like this? Mhh...
-
--
-5-
-5-5
-5e-5

Yeah I don't know what the best behavior would be. We get a bunch of issues from people being able to enter values that are not allowed or just weird.

**Comment by AdelheidF** [comment]
Maybe it would help having this one fixed too: 
https://github.com/Esri/calcite-components/issues/3003 (when I programmatically update values in the input they don't show)

Then we can better 'fix' the values in the box to what we want to allow. Most number input min/max ranges use simple numbers like 1 to 10 or 1 to 100. In those cases I don't have to worry about numbers like -5e-5.

**Comment by benelan** [comment]
> Yeah I don't know what the best behavior would be. We get a bunch of issues from people being able to enter values that are not allowed or just weird.

What is currently installed should fix that though, because those weird inputs are parsed out of the actual value. So even if the component looks a bit weird, it won't break someone's app. And restricting it to two hyphens will at least make it less weird. Past changing that, I think any other enhancements/fixes should go into a new issue.

**Comment by AdelheidF** [comment]
beta.74 only allows 2 hyphen, verified
