### ISSUE TITLE
Button Clear and Button Transparent style fixes

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#309]
### Button Clear and Button Transparent style fixes

**For light theme:** 

1. Clear Light, Outline Light: change hover and press states to ui-foreground-press (#eaeaea)

**For dark theme:**  

1. Change all Outline buttons to use ui-foreground-dark (instead of ui-background-dark)

2. Change border color on Outline Dark and Clear Dark to use ui-foreground-hover-dark  (#353535) _IDLE STATE only_

3. Clear Dark, and Outline Dark: change hover and press states to ui-foreground-press-dark (#404040)

**Comment by macandcheese** [comment]
Sounds good...

@julio8a - should we update the nomenclature in https://github.com/Esri/calcite-colors/blob/master/colors.scss to just use incrementing numbers instead of hover / press? It seems like we are no longer using those 1:1, and it's getting a bit confusing to use variables that don't match their meaning. Seems like we could extent the "-border" range to 4,5 to replace hover/press for that, and do something similar for foreground-1/2/3 to replace idle/hover/press.

**Comment by julio8a** [comment]
Yeah, It'll make the 3 colors states (idle, hover, press) more flexible.

**Comment by julio8a** [comment]
in master now. Closing.
