### ISSUE TITLE
Enhancement: [calcite-tree] add selection-mode "none"

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3121]
### Description
Support a calcite-tree selection-mode of "none", for displaying a hierarchical list of tree-items which display no icons on hover/focus, and do not allow any items to be selected.

### Acceptance Criteria 
A new selection-mode of "none" is added to the [TreeSelectionMode](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tree/interfaces.ts#L5) type values. When a tree has selection-mode "none", no child tree-items can be selected, and no icons appear on :hover or :focus.

### Relevant Info 
Related issue tied to this request: #2210 (cc @bpatterson88)

#### Which Component
calcite-tree, calcite-tree-item

#### Example Use Case
(See screenshots provided in #2210)

**Comment by caripizza** [comment]
Here's one example I found in the wild of "none" selection-mode with IntegralUI's TreeView component for Angular:
https://www.lidorsystems.com/support/articles/angular/treeview/treeview-multi-select.aspx

**Comment by macandcheese** [comment]
This implementation from SAP also uses "none":  https://sap.github.io/ui5-webcomponents/playground/components/Tree/

**Comment by ellenupp** [comment]
Use case for Dashboards:
We are using a tree to represent the layout of the elements in the dashboard. The tree does not need a selection state. Clicking a tree item should place focus on that item but not otherwise change its state. Tree items don't need bullet point and instead child items have a custom icon. 
![image](https://user-images.githubusercontent.com/14304581/135142106-bee99dcb-0f19-488c-9d85-6ba50112066b.png)

**Comment by paulcpederson** [comment]
We also have a use case for this. Seems pretty straight forward, I could try to add this?

**Comment by benelan** [comment]
Sure, @paulcpederson, we always appreciate your help!

**Comment by jcfranco** [comment]
Stealing this one... 👿

**Comment by geospatialem** [comment]
Verified in beta.92 👍🏻
