### ISSUE TITLE
calcite-button - don't run onclick if button is disabled

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#319]
Should be the same behavior as a native button which doesn't allow click on a disabled button.

cc @driskull

**Comment by driskull** [comment]
Agreed. clicking on a native button that is disabled doesn't fire the onclick. We should probably do the same.

**Comment by driskull** [comment]
@AdelheidF looking at the code, I'm not sure we can stop the clickEvent. The clickEvent is added by you and not something we control. If it were a custom event, we could control it.

@macandcheese you want to chime in?

It does seem like the "form" use case could be stopped when disabled though.

I'm also seeing that the slider could probably be prevented when disabled as well.

**Comment by AdelheidF** [comment]
>  I'm not sure we can stop the clickEvent.

OK, thanks for looking into it.

**Comment by macandcheese** [comment]
Yeah, we could surely figure something out to prevent disabled buttons from firing an onClick added in the DOM, although it might be a bit messy since AFAIK you can't prevent the onClick from firing if it's added in the DOM, you can only determine/alter the value of the onclick attribute, something like...

- on load, store the onclick attribute if provided
- if the button is disabled, clear the attribute
- add a watcher for `disabled` (or, use componentWillUpdate ? both seem to work)
- swap between the initial provided value and empty value depending on state

I have this working locally - not the prettiest but it works.

```
  componentWillLoad() {
    this.initialOnClick = this.el.getAttribute("onclick");
    this.requestedOnClick = !this.disabled ? this.initialOnClick : false;
  }

  @Watch("disabled") disabledWatch() {
    this.requestedOnClick = !this.disabled ? this.initialOnClick : false;
  }
...
 <Host dir={dir} hasText={this.hasText} onclick={this.requestedOnClick}>
...
```

Re: disabled buttons in forms, they currently won't "submit/reset/", but the above applies if there's a provided onclick in the DOM. Check me on that if I'm wrong but I couldn't get a form button to submit if it was disabled.

**Comment by macandcheese** [comment]
Not installed after discussion: https://github.com/Esri/calcite-components/pull/320

**Comment by krychu** [comment]
This is a bit unexpected because it's different to the behaviour of native button. A common use-case is to set `onclick` and manipulate `disabled` dynamically in the app, based on some condition. It's inconvenient to also needing to remove `onclick`, `ondbclick` or pass them empty handlers.

Would it make sense to keep the behaviour of calcite button consistent with the native button in this case?

wdyt @AdelheidF @driskull @macandcheese ?

**Comment by AdelheidF** [comment]
I don't have a strong opinion either way, we have conditional event handlers in other places as well.
