### ISSUE TITLE
Bug: `CalciteSelect.selectedOption` can become stale

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3239]
### Actual Behavior
If a `<calcite-select>` component's selected option is chosen in a way that does not trigger the `calciteSelectChange` event, the component's `selectedOption` property points at the old option instead of the new one.

### Expected Behavior
The `<calcite-select>` component's `selectedOption` property always points at the `<calcite-option>` element that has the `selected` attribute.

### Reproduction Steps and Sample

_Sample_: https://jsbin.com/meveyowobi/edit?html,js,output

1. Visit the sample jsbin.
2. The sample has a `<button>`, a `<calcite-select>`, and a `selectedOption.value` output.
3. Click on the `<calcite-select>` element and choose the "two" option. The `selectedOption.value` output updates to show `"two"`.
4. Now, use the `<button>` to toggle the selected option by setting the `selected` attribute directly (in this case, via Ember's attribute binding). The `<calcite-select>` component's `selectedOption` value is re-polled, but the `selectedOption.value` output still shows `"two"`.

### Relevant Info
The test case could further be reduced by adding/removing the `selected` attribute manually to the `<calcite-option>` elements.

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [ ] CDN
- [ ] NPM package

**Comment by nwhittaker** [comment]
@benelan, I updated the sample to pull in the latest `@next` version (see [snapshot](https://jsbin.com/zojonalera/edit?html,js,output)), and I agree that it does not look fixed there.

**Comment by jcfranco** [comment]
This was fixed in the previous milestone. The original repro case is a bit misleading. If you swap out the components for their native equivalents, you can see they behave the same now (see https://jsbin.com/wofovax/2/edit?html,js,output):

**using `<select>`**
![select-selectedOption-native](https://user-images.githubusercontent.com/197440/147369756-9d05485d-4ef4-47eb-afd7-de1c8187674c.gif)

**using `<calcite-select>`**
![select-selectedOption](https://user-images.githubusercontent.com/197440/147369757-8f3e627c-98e7-45cd-a7d5-48faf23844ae.gif)

Compare the above with the original repro case:

![select-selectedOption-broken](https://user-images.githubusercontent.com/197440/147370839-fdd6d869-5e32-40fa-ae94-df594e1f2f23.gif)

**Comment by benelan** [comment]
verified using Franco's sample
