### ISSUE TITLE
Bug: calcite-value-list duplicates item when dragging an item to the end of the list

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3247]
### Actual Behavior

When dragging a `<calcite-value-list-item>` to the end of the list, the item is duplicated.

### Expected Behavior

When dragging a `<calcite-value-list-item>` to the end of the list, the item should not be duplicated.

#### Code setup

1. Create a `<calcite-value-list drag-enabled>`
2. Use `<calcite-value-list-item>`s that are backed by a computed property that creates new objects
3. Listen for 'calciteListOrderChange' event on the `<calcite-value-list>` and reorder the backing list
3. Ensure there are at least two list items

#### Reproduction steps

1. Drag item to the end of the list
2. Observe item is duplicated

_Sample_:

1. [codepen](https://codepen.io/jmanke/pen/YzxXoXR)

### Relevant Info

- Bug was first found in EmberJS and the code sample uses EmberJS

_Version_: `@esri/calcite-components@<1.0.0-beta.67>`

- [x] CDN
- [ ] NPM package

cc @vijayendranj

**Comment by jmanke** [comment]
It looks like using  'key' inside of {{each}} will prevent items from duplicating. For example:

`{{each this.items key='id' as |item|}}`

After adding 'key' inside of {{each}} the calcite-value-list with draggable items works as intended.

**Comment by jcfranco** [comment]
The list is working as expected. The observed issue is caused by a missing [`key` option (Ember)](https://api.emberjs.com/ember/2.6/classes/Ember.Templates.helpers/methods?anchor=each#:~:text=li%3E%0A%20%20%7B%7B/each%7D%7D%0A%3C/ul%3E-,Specifying%20Keys,-The%20key%20option) for elements that are generated from an array. This helps Ember keep track of nodes between renders.

Once a key is provided

```hbs
{{#each this.computedValues key="label" as |value index|}}
```

the list works as expected: https://codepen.io/jcfranco/pen/bGrJYoW?editors=1000
