### ISSUE TITLE
Bug: calcite-alert stays open beyond animation end when another alert is added

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#3366]
### Actual Behavior

When an auto-dismiss calcite alert is open and second alert is is added, there seems to be a delay between the progress bar animation ending and the first alert closing. You can see in this video:

https://user-images.githubusercontent.com/6539297/139159791-544070bc-0eec-456f-888c-2fb36a02bdf7.mov

### Expected Behavior

I would expect the alert close behavior to be the same regardless of when a new alert has been added.

### Reproduction Steps and Sample

_Sample_:

1. Go to https://codepen.io/noahmulfinger/pen/rNzwLRK?editors=1010
2. Click on the `Add alerts` button and you will see the same behavior as in the above video.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-68`

- [x] CDN
- [x] NPM package

**Comment by benelan** [comment]
@macandcheese can you take a look at this one for design? I don't think there should be a close animation if there is another alert already queued. There was no close animation before this fix, we just needed to remove the delay before the progress bar started moving. I used Noah's sample and changed the version to `next`.

**Comment by macandcheese** [comment]
So, this is kind of a weird one. Because an individual alert animates in, the alert "object" should animate out before another one can replace it. If we didn't do that, we'd be replacing the content of the alert vs. replacing the alert itself, which the animation infers.

That said - it's not a great interaction. Ideally when we handle multiple queued alerts with this update: https://github.com/Esri/calcite-components/issues/2835, we can have queued alerts animate in "behind" and then the animation for the queued alert becoming active will be more of a "move to front", with the dismissed alert animating out.

I realize that probably doesn't make sense, the image in the linked issue may help. For now I think we can leave it until that's implemented.

**Comment by benelan** [comment]
Thanks for looking Adam. This is verified on `next` then.
