### ISSUE TITLE
Icons are not appearing in a button in iOS

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#3434]
### Actual Behavior

A pair of buttons with icons and no text are invisible in iOS (Safari & Chrome) until clicked; they appear successfully in Windows (Chrome & Firefox)

Windows vs. iOS:
![image](https://user-images.githubusercontent.com/2125181/140413988-34098038-a424-481b-bf78-50af66d323df.png)  ![image](https://user-images.githubusercontent.com/2125181/140414107-eb86508c-ea10-4bbc-ae9c-bf401457e892.png)

### Expected Behavior

Expect iOS displays to match Windows displays

### Reproduction Steps and Sample

_Sample_: https://codepen.io/miketschudi/pen/KKvQmQX

### Relevant Info

Windows 10, iOS Safari 15.1

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-61`
Windows: ![image](https://user-images.githubusercontent.com/2125181/140415597-0765acbb-6b8d-4687-9b66-41c353a0b514.png)
iOS: ![image](https://user-images.githubusercontent.com/2125181/140415748-37677099-f0bb-402a-acaf-971fd6e200c5.png)

**Comment by jcfranco** [comment]
@macandcheese Hope you don't mind, but I dug a bit into this and found out that this does work in the latest version with `color=neutral` (formerly `dark`): https://codepen.io/jcfranco/pen/bGovBpo?editors=1000

In the repro case, since an invalid color value is used, the parent button (in the shadow DOM) doesn't get a color set, so the icon picks up the color from the default button styling. iOS's default button color happens to be white, so that's why it looks like the icons are gone.

I'll go ahead and close this since this is technically working as expected. 

Hope everyone has a very Happy New Year! 🎉 🍾 🎩

**Comment by MikeTschudi** [comment]
@jcfranco, thanks for solution; works perfectly!
