### ISSUE TITLE
Date Picker is not localized for Bulgarian (bg)

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#3602]
AGOL introduced Bulgarian as a new language for this release and it looks like Calcite Date Picker has not been updated with it:
Locale = bg

https://codepen.io/zmatheson/pen/YzrPwdb?editors=1010

cc @jcfranco

**Comment by zaramatheson** [comment]
### Description
AGOL introduced Bulgarian as a new language for this release and it looks like Calcite Date Picker has not been updated with it:
Locale = bg

### Acceptance Criteria 

Support Bulgarian Languague

### Relevant Info 

#### Which Component
calcite-input-date-picker 

#### Example Use Case

ArcGIS Online Map Viewer Time Slider, Filter,

**Comment by driskull** [comment]
@jcfranco @paulcpederson Do you know the process for localization within calcite for this? Its kind of an outlier because we don't do any other localization within calcite.

**Comment by bsvensson** [comment]
FYI - The actual Bulgarian CLDR strings can be found in https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-modern/main/bg/ca-generic.json
Compare the English (World) strings in https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-modern/main/en-001/ca-gregorian.json

**Comment by jcfranco** [comment]
Deferring to @paulcpederson since he introduced those localization files. We should add this info to a wiki page for posterity. cc @benelan

**Comment by paulcpederson** [comment]
We had Babak Bolour and Rajeev Krishnan send us these json files. I spec'd what we'd need and they delivered a folder of them which I pr'd in.

**Comment by paulcpederson** [comment]
Now that we dropped ie11 we could theoretically start using Intl for this as I think the api's have good enough support IIRC, but I could be wrong on that one...

**Comment by driskull** [comment]
That would be ideal so we don't have to manage this :)

**Comment by jcfranco** [comment]
Thanks for the info, @paulcpederson! I'll work on a prototype to see if we can leverage Intl. In the meantime, I'll reach out to get the missing localization file.

**Comment by jcfranco** [comment]
Early prototyping shows that `Intl` does not have the necessary info to replace the localization files 1-1. Some items are not available or don't match from [`Intl.DateTimeFormat.formatToParts`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts):

* `default-calendar` - this may be fine since it doesn't seem to be used at the moment
* `weekStart` - missing 🚫
* `unitOrder`/`placeholder` - it looks like these could be inferred from the order of `formatToParts`, but we'd need to confirm
* `days.abbreviated` - missing 🚫
* `numerals` - this could be fine if we format each day individually
* `days.narrow`/`months.narrow` - the `short` date style show numbers
* `year.suffix` - this could be obtained from the year separator, but we'd need a list of locales to do this for since all of them seem to have a separator

The rest from the `DateLocaleData` interface can be generated dynamically.

IMO, not having `weekStart` is a showstopper.

**Comment by driskull** [comment]
bummer :(

**Comment by AdelheidF** [comment]
Changed the codepen to beta.74 and now I see this. I don't think it's correct for Bulgarian, the input box doesn't show yyyy.
The calendar is good now.

![image](https://user-images.githubusercontent.com/44481292/149196670-18509ff2-44a7-4ef7-b652-ad7aec29eb61.png)

**Comment by jcfranco** [comment]
> the input box doesn't show DD.MM.YYYY, like in all other languages.

I believe this is expected. The placeholder format comes from the bg localization file. cc @raje9276

> I also noticed none of the Chinese language codes work. They stay English, see codepen.

I will create a separate issue for this.

**Comment by AdelheidF** [comment]
BG is good: https://www.localeplanet.com/icu/bg-BG/index.html
