### ISSUE TITLE
Changes to calcite-label's status property are not propagated to child calcite-inputs

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#3613]
### Actual Behavior

If you wrap a `calcite-label` around a `calcite-input` or a `calcite-input-message` they will inherit the `status` prop of the `calcite-label`. But if you then programmatically change the value of `status` on the `calcite-label`, the change will not flow down to the input or the message.

### Expected Behavior

I expected the input and input message `status` to stay in sync with the label's `status` prop.

### Reproduction Steps and Sample

Here is a codepen to satisfy the robots: https://codepen.io/mjuniper/pen/gOGbyzJ

But please see the test case and STR in [this](https://github.com/mjuniper/calcite-components/pull/2) PR/branch because I think it better illustrates the issue.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-next.312`

I can work around this issue by also binding the `status` prop of calcite input to my same `Prop` or `State` but I was surprised by this and it seems like a bug.

**Comment by mjuniper** [comment]
I will provide a codepen but I really think the branch better illustrates the problem because it mainly becomes a problem when you are building a stencil component out of calcite components and you have the `status` prop of a label _bound_ to a `Prop` or `State` in your component.

**Comment by Elijbet** [comment]
I noticed that the status on the input has styling associated with it, but the one on label doesn't. These two aren't connected. Can we discuss whether we should have a status property on the label, and if yes then what would the behavior be?

**Comment by driskull** [comment]
@eriklharper @jcfranco Do we need the status property on the label? It doesn't seem to do anything by itself

**Comment by eriklharper** [comment]
It doesn't appear that `status` needs to be declared as a `@Prop` on label because the input looks up the value with `getElementProp` anyway and when label is mutated, a re-render occurs in label, but that doesn't trigger a passing of the new status down to its children.

The fix for this would either require adding logic to label to pass the new status value down on mutations to the children (which is messy since it would involve DOM querying for slotted content), or there might be a way to fix this in the individual input components, but that's assuming we want to continue to support this kind of pattern.

We should probably revisit this pattern to see if this is something we want to continue doing.  It looks like the use of `getElementProp` to search up the DOM tree occurs in about 29 places in Calcite, so this wouldn't exactly be a trivial thing to stop doing.

**Comment by driskull** [comment]
Yeah, we need to discuss this pattern. A child component won't know when a parent changes.

**Comment by jcfranco** [comment]
I think this got left out after we decided and refactored components to have explicit props. `getElementProp` was used early on for components using pass-through props, but this isn't ideal for the reasons you've mentioned above.

**Comment by driskull** [comment]
from meeting...

- We will deprecate Status on label
- We will refactor usage of getElementProp (Epic issue)

**Comment by macandcheese** [comment]
> * We will deprecate Status on label

Could we preserve this property on label? It would allow us to style `invalid` label text which has been requested (but proceed with the removal of children using `getElementProp`)

**Comment by driskull** [comment]
Yeah, if we preserve the property, we should have it actually do something on the component.

**Comment by jcfranco** [comment]
This has been addressed by https://github.com/Esri/calcite-components/issues/3755. To summarize,  `HTMLCalciteLabelElement#status` is deprecated and it is now recommended to set the `status` on `calcite-input` and `calcite-input-message` directly.

Closing.
