### ISSUE TITLE
Conventions: Should use a CSS naming convention like BEM?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#37]
Breakout from https://github.com/ArcGIS/calcite-components/pull/32#discussion_r290388120

Discuss. I'll flesh this out later. 😄

**Comment by pr3tori4n** [comment]
IMO no. Since the shadow dom encasulate's the styles, we're free to go back to using simple selectors since we don't have to worry about name-clashing, clobbering, bleed-out whatever.
`.name {}` or even a tag selector like `a {}` is fine. Using BEM would mean not benefiting from one of the coolest feature's the shadow dom provides.

If you're worried about polyfilled browsers - you don't have to. The compiler generates unique class names for you.
