### ISSUE TITLE
[IE11] Loader - Loaders don't appear, styling is broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#371]
Indeterminate loaders don't seem to show at all, styling on those that do doesn't really work. I know we have the open PR for a circle, @julio8a do you have any insight on if that PR is still necessary? 

<img width="415" alt="Screen Shot 2020-03-06 at 3 39 35 PM" src="https://user-images.githubusercontent.com/4733155/76131357-024bb980-5fc3-11ea-9ff0-029158e36d4b.png">

**Comment by julio8a** [comment]
Yes, we still need to swap it out for the circle.

**Comment by paulcpederson** [comment]
Now that we are going to a circle, we can accomplish this with multiple `circle` elements that are rotated. The square version had to use the dash-offset as the animation because you can't rotate the square. But using multiple circle elements stacked on one another I think will also work in ie11 and be lighter-weight.
