### ISSUE TITLE
deprecate `disablePadding` , `noPadding` in favor of CSS variables

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3860]
### Question
Label currently has a `disableSpacing` property which "eliminates any space around the label".

```
:host([disable-spacing]) {
  .container {
    @apply gap-0 m-0;
  }
}
```

There has been some call to introduce this approach to other components. Should we? Or is this a broader issue?

Some points from a discussion are:
* Components shouldn't have margins at the :host or .container level.
  *  Label currently does this.
* Spacing is core part of a UI's rhythm and readability.
  * It's also important to retain spacing relative to scale.
* If our spacing is causing problems with our own stuff, we should probably fix that.

Some have suggested that a systematic solution for spacing might be the better solution, e.g. a spacing component, utility classes, etc.

Something else to consider is that when "known components" are children, inter-component spacing should be considered as helpful, e.g. **ListItem** inside a **List** or **Action** inside **ActionBar**.

### Update 

- As discussed in teams channel, we will deprecate `disablePadding` , `disableSpacing`  & `noPadding` props across the repo and replace them with CSS vars instead
- Any new requests for customizing spacing will be addressed based on user feedback.

**Comment by driskull** [comment]
> Something else to consider is that when "known components" are children, inter-component spacing should be considered as helpful, e.g. ListItem inside a List or Action inside ActionBar.

Yes, we should space children but not parent components. In this case, it's probably best if the parent handles the spacing and the children don't have spacing on their own.

**Comment by macandcheese** [comment]
I agree that components should not "space themselves". 

I think `calcite-label` is a bit of an outlier because it is so often a part of a larger group of multiple `calcite-labels` . 

If we had a `calcite-label-group` type component, we could offload the spacing responsibility to that parent, and continue to have consistent rhythm in forms, while keeping a single `calcite-label` free of any applied margins.

**Comment by asangma** [comment]
> it's probably best if the parent handles the spacing and the children don't have spacing on their own.

Agreed.

**Comment by driskull** [comment]
> If we had a calcite-label-group type component, we could offload the spacing responsibility to that parent, and continue to have consistent rhythm in forms, while keeping a single calcite-label free of any applied margins.

I think that is warranted :) Some type of group component.

**Comment by asangma** [comment]
The pattern for "[something]-group" sounds good to me.

And I agree about not wanting to do `calcite-form` unless it had the implied logic.

**Comment by driskull** [comment]
At some point we might need a `fieldset` equivalent component.

**Comment by eriklharper** [comment]
For context on the `disable-spacing` attribute, that was added in order to allow browsers that don't support flex gap to be able to specify spacing manually: https://github.com/Esri/calcite-components/blob/cedcc695cb318525a7d735c2db72068260fa8d27/src/components/calcite-label/readme.md#browser-caveat.

The tricky thing about label is that it can be used standalone or as a parent.  Label's spacing CSS is setup to accommodate the parent scenario so that there is adequate space between the label text and the input it is wrapping.  The way I see it, it is already a "group" component.

Also, the pattern for having "group" components that perform spacing on their children is a pattern that does exist currently, namely the `calcite-radio-button-group` element, so there is prior art to reference on that idea.

**Comment by eriklharper** [comment]
> If we had a calcite-label-group type component, we could offload the spacing responsibility to that parent, and continue to have consistent rhythm in forms, while keeping a single calcite-label free of any applied margins.

Correct me if I'm wrong, but currently `calcite-label` doesn't apply any margin styles to itself.  It only spaces its children by targeting the container div so that when it is used in a parent (wrapping) scenario, there's no need to put in extra markup or styles to space the label text away from the input the label is wrapping.

**Comment by driskull** [comment]
> For context on the disable-spacing attribute, that was added in order to allow browsers that don't support flex gap to be able to specify spacing manually:

Do we still support any of these browsers? Maybe we can just deprecate and remove this property?

**Comment by eriklharper** [comment]
I suppose it might be safe to remove based on this.  We only support 2 major versions back from the current versions right?

![image](https://user-images.githubusercontent.com/821864/148434608-b8a1ae1c-b66c-4ea7-8797-ca8a2357c0e5.png)

**Comment by benelan** [comment]
Do we have any action items for this issue? If not I will convert it into a discussion.

**Comment by driskull** [comment]
I believe the action item was to remove the `disableSpacing` property from `label`.

We will have classes or a grouping component outside of the label.

**Comment by macandcheese** [comment]
Agreed - I don’t think we should remove or deprecate the property before adding either / both of the above - to avoid breaking a lot of current designs.

**Comment by macandcheese** [comment]
@benelan Can this be closed? We removed this property from label and are updating the remaining (valid) instances to be consistent: https://github.com/Esri/calcite-components/issues/4824

**Comment by anveshmekala** [comment]
- As discussed in the team's channel, we will deprecate `disablePadding`, `disableSpacing` & `noPadding` props across the component in the repo and replace them with CSS vars instead. 
- Any new additions to the component will be assessed based on user feedback.

**Comment by anveshmekala** [comment]
@benelan  can we repurpose this issue or  close this and open a new one?

**Comment by benelan** [comment]
Let's repurpose this one to keep the context in the comments above. Can you change the title and add something at the top of the issue body to represent the new action items?

**Comment by jcfranco** [comment]
@anveshmekala can this be marked as installed? Also, can you update the title as @benelan suggested above? Thanks! 🙌

**Comment by benelan** [comment]
verified in storybook's doc, e.g. [loader](https://esri.github.io/calcite-components/?path=/docs/components-loader--simple)
