### ISSUE TITLE
calcite-tabs component not throwing events when used inside a custom web component

### ISSUE THREAD

**Issue by RalucaNicola** [Esri/calcite-components#3949]
### Actual Behavior

I'm using a calcite-tabs component inside of a custom web component. Clicking on the tab titles does not switch them (the same tab remains active all the time).

### Expected Behavior

I would expect that the current active tab switches based on the tab title that the user clicks on.

### Reproduction Sample

https://codepen.io/ralucanicola/pen/mdBvbem?editors=1010

### Reproduction Steps

1. Click on Eligibility and notice that neither the eligibility tab title, nor the tab itself change.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.74

### Relevant Info

Not a regression. Tested on Chrome, macOS Catalina.

### Source

- [X] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Looks like the tab-title's [tab change handler](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tab-title/calcite-tab-title.tsx#L189) needs to check the event's `composedPath` instead. It doesn't work when wrapped in another custom element because the event is retargeted, so the target is not the tab-title, but the wrapping element.

**Comment by benelan** [comment]
verified on next
