### ISSUE TITLE
Include slot for inline 'info icon' before or after label text.

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#4155]
### Description

For analysis, we will need to provide parameter-based help for various inputs in the form. We'd like to include an inline action that triggers a popover with the helpful information in it.

### Acceptance Criteria

- [ ] There is a way for developers to include an icon in the label
- [ ] You can include the icon before or after the label text
- [ ] The icon can be used to trigger a popover

### Which Component

Label

### Example Use Case

![image](https://user-images.githubusercontent.com/12564905/155204856-85cc059b-523b-454d-9921-5304d26db31e.png)

**Comment by macandcheese** [comment]
Thanks for submitting, this is a common use case ... could you add designs for the other layouts of input - inline and inline-space-between? 

Additionally, the label text (or multiple strings) and child control can be placed in any order, so comps that show some less common arrangements could help us understand where to position the named slot.

I anticipate this will be very commonly used and because of the often tight confines of _where_ it will be used we may want to be somewhat strict in our styling ruleset of the slot. To complicate things for ya @mitc7862 - the design should probably encapsulate some of what was proposed here https://github.com/Esri/calcite-components/issues/2793 - These two elements will likely co-exist at times.

**Comment by macandcheese** [comment]
When you say build custom input labels, do you mean just slot the div inside a `calcite-label` like this? 

https://jsbin.com/zexapenizo/1/edit?html,output


I think the issue with potentially styling or placing a named slot is that, like in Mitch's example, there are many potentially valid placements for the tooltip.

**Comment by TheBlueDog** [comment]
We could certainly start with one as an opinionated pattern that we all use.

**Comment by TheBlueDog** [comment]
Is there any status on this? Field Maps is having to handle this currently with custom inputs.

**Comment by macandcheese** [comment]
No update at this time. As an implementation note for when this is looked at - the label functionality to focus the child control may need to have an "exclusionary click zone" or something along those lines to ensure clicking on a, tooltip trigger, for example, doesn't focus the control.

**Comment by geospatialem** [comment]
Adding the slot will require a major refactor, and will be prioritized after next month's release. cc: @ashetland, @Elijbet 

Once prioritized the effort should be coupled with #2793 and #5079.

**Comment by ashetland** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/5079.
