### ISSUE TITLE
Event dispatched for programmatic change if input has focus

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4229]
### Actual Behavior

If a `calcite-input` element has focus, and its value is changed programmatically, it will dispatch a `calciteInputChange` event when it's blurred.

### Expected Behavior

A `calciteInputChange` event is not dispatched because the value was not changed due to a user interaction.

### Reproduction Sample

https://ember-twiddle.com/5f817823e90d22b8417ae66304a80c52

Ember sample forked from `calcite-components-examples` https://github.com/eriklharper/calcite-4229-repro

### Reproduction Steps

1. Visit the sample and open the browser's dev tools console
2. Click the "Seed value with focus shift" button
3. After focus shifts to the input, blur the input in some way
4. Observe that `"didChangeSeededInput"` appears in the console indicating that the input's `calciteInputChange` handler was hit

### Reproduction Version

1.0.0-next.415

### Relevant Info

Related/parent issue: https://github.com/Esri/calcite-components/issues/2033.

The example is somewhat contrived, but Ember has a data-down, action-up pattern that makes it easy to craft a scenario where focus can shift to an input before a previous action has finished updating the input's value.

**Comment by jcfranco** [comment]
@eriklharper Do you think you can take a look at this? This block looks suspect: https://github.com/Esri/calcite-components/blob/ffff3d5933d3a00776adc90d78d2cb449ba7920a/src/components/input/input.tsx#L449-L451

**Comment by eriklharper** [comment]
@nwhittaker since this is a contrived example and is discouraged in Ember's own documentation, I'm curious if you are able to workaround this by using a modifier?

I tried something like this which works to resolve this for me locally in our Ember example app:

First install `ember-modifier` with:

`ember install ember-modifier` or `npm i --save-dev ember-modifier`

app/modifiers/focus-calcite-input.js
```
import { modifier } from 'ember-modifier';

export default modifier((element) => element.setFocus());
```

app/controllers/application.js
```
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class ApplicationController extends Controller {
  @tracked seededValue

  @action seedValueWithFocusShift() {
    this.seededValue = Math.random();
  }

  @action didChangeSeededInput() {
    console.log('didChangeSeededInput')
  }
}
```

app/templates/application.hbs
```
<p>
  <calcite-button {{on 'click' this.seedValueWithFocusShift}}>
    <span>Seed value <em>with</em> focus shift</span>
  </calcite-button>
</p>

<calcite-label>
	Seeded value
	<calcite-input
    {{focus-calcite-input this.seededValue}}
    id="seeded"
    value={{this.seededValue}}
    {{on 'calciteInputChange' this.didChangeSeededInput}}
  ></calcite-input>
</calcite-label>
```

The issue is that the focus handler is being called before the component instance in the DOM has a chance to receive the updated `seededValue` so the internal state of the input component isn't correctly set in the blur handler, which checks to see if the value changed between the time it was focused and blurred (which is currently being used to determine if a user typed a value versus it being changed programmatically), resulting in an incorrect change event being emitted.

I still think the logic is flawed around how the input knows if its value changed as a result of user input versus a direct assignment through javascript, so I think this is still an issue that requires a more elegant solution to this contrived problem, but was curious if you had tried this approach that Ember recommends for performing side effects like focusing DOM elements after state changes.

**Comment by eriklharper** [comment]
Cool thanks for that additional context and insight into your specific problem!  I'm working on a fix that attempts to more directly determine whether a change is the result of user interaction or not, which should resolve this for good.

**Comment by benelan** [comment]
verified on next
