### ISSUE TITLE
Tooltips in beta 81 have a couple new unwanted behaviors

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#4399]
### Actual Behavior

Tooltip no longer closes when the target, e.g. action or button, is clicked.

Tooltip randomly does not hide when target is no longer hovered, with occasional long hide delay. May result in several tooltips visible at once.

When using `tooltip-manager` with `slot="header-actions-end"` wrapping an action in a panel the tooltip is behind the content of the panel. Examples:

![image](https://user-images.githubusercontent.com/14297903/163067743-1bad7987-7c61-4d8f-8041-4511ded41515.png)

![image](https://user-images.githubusercontent.com/14297903/163067833-fedde8c9-1c2a-4aaf-8b08-a5c39906cf8a.png)

### Expected Behavior

Excepted tooltips to behave as they did prior to beta 81.

### Reproduction Sample

https://codepen.io/COV-GIS/pen/VwyGmZb

### Reproduction Steps

1. Click on a header actions and the tooltip does not close.
1. Hover over a header action and the tooltip is behind the panel's content.
1. Switch hover between actions and one or both tooltips may get stuck visible or have delayed hide delays. Low occurrence and seems to be a load/hydration problem as it has the behavior after app load or it doesn't.

### Reproduction Version

1.0.0-beta.81

### Regression?

1.0.0-beta.80

**Comment by driskull** [comment]
@jcfranco the stacking part of this issue is likely related to the changes to panel with z-indexes removed.

**Comment by jcfranco** [comment]
@COV-GIS You should move the tooltips outside of the manager. https://codepen.io/jcfranco/pen/KKZJggV?editors=1000 Also worth noting that you do not need to use `overlay-positioning='fixed'` since there's no fixed-positioned nor scrolling parent.

@driskull @benelan @macandcheese I noticed that the stories and usage examples in the repo have tooltip as a sibling to the manager, but the [SDK example](https://developers.arcgis.com/calcite-design-system/components/tooltip/#sample) has it as a child. We should update the latter, right?

**Comment by macandcheese** [comment]
@jcfranco yes we can update that - do you expect this to land before 82? 

https://github.com/Esri/calcite-components/pull/3611

**Comment by driskull** [comment]
Thanks for the feedback @COV-GIS 

> Tooltip no longer closes when the target, e.g. action or button, is clicked.

This issue https://github.com/Esri/calcite-components/issues/4294 changed so that tooltips don't close on click. I think we can add a property to do this for tooltips that feel its necessary. What do you think @jcfranco ? Maybe something like `closeOnClick`?

> Hover over a header action and the tooltip is behind the panel's content.

I think this one is related: https://github.com/Esri/calcite-components/issues/3724 & https://github.com/Esri/calcite-components/pull/4182

This might need to be separate issue.

> Switch hover between actions and one or both tooltips may get stuck visible or have delayed hide delays. Low occurrence and seems to be a load/hydration problem as it has the behavior after app load or it doesn't.

@COV-GIS I'm not seeing this one. can you share a gif or video? I'm probably not reproducing it correctly :)

**Comment by COV-GIS** [comment]
Methinks this was not an issue with tooltip @driskull. Probably should not have included it as it was not in the pen rather in a widget. I suspect is was a rendering issue related to how I was generating ids for the target along with property watching and how some events were being wired up causing lots of unnecessary rendering in general. I should have commented on this to let the thread know when I discovered and fixed those issues. This can safely be disregarded.

A click on close property would be appreciated if it is determined to be worth implementing.

Thanks.

**Comment by macandcheese** [comment]
> A click on close property would be appreciated if it is determined to be worth implementing.

I still think this would be worth adding (whether it is `click-on-close` or `disable-click-on-close`), we've seen a few reports of this being confusing since the change was made and there are instances of both behaviors making sense.

**Comment by driskull** [comment]
Agreed!

**Comment by driskull** [comment]
Created: https://github.com/Esri/calcite-components/issues/4682 for panel issue.

**Comment by geospatialem** [comment]
Verified the `closeOnClick` property and `close-on-click` attribute for calcite-tooltip on `next`. ✅
