### ISSUE TITLE
Update styling on Calcite Date

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#446]
Update styling to match design for Calcite Date. See images

additionally, focus hover updates: next/prev buttons are missing blue inset focus, 2020/year needs some sort of hover, suggestion same as focus but color is #dfdfdf

![image](https://user-images.githubusercontent.com/14083530/78612461-3e6e7600-781e-11ea-9ff8-ed8d0dc9f090.png)

![image](https://user-images.githubusercontent.com/14083530/78612481-4d552880-781e-11ea-8fb7-b371d663e947.png)

**Comment by macandcheese** [comment]
Feedback on these proposed changes:

- I'd prefer to leave the dividing line between the date / year and day list. It better communicates the hitbox of the next / prev buttons and more closely mirrors the design we have for Modal

- Making the "out of range" dates invisible doesn't make sense to me, they are selectable dates - removing them completely will cause users to navigate to another month just to select an adjacent date. I think the treatment @paulcpederson added was nice - it's clear they are in a different month (if the numbers themselves didn't indicate that), while maintaining clickability.
--  The current "min/max" example to me at least communicates they are not selectable - maybe that would make more sense for not showing (and hiding the next / prev buttons as well in that use case)

- The alignment of the next / prev carets in the updated design doesn't seem to align with the left and right-most day or dates, it kind of creates a staggered effect. Perhaps we could just ensure they are centered above their respective left and right-most day?

- I think @paulcpederson already implemented the above hover / focus states?

- If we were to change the day display to a single later, I'd suggest just having that as an option, rather than a default. A browser-default date input displays the "three letter" abbreviation - not sure what impact that'd have on translations or locales.

- 700 is bold, so that may be a little jarring.

**Comment by bstifle** [comment]
here is the latest 
@macandcheese  @julio8a 

![image](https://user-images.githubusercontent.com/14083530/78705242-10db0880-78c2-11ea-9f5b-e0372258190d.png)

**Comment by bstifle** [comment]
^regarding that last image, i think keeping the days of the week BOLD would be better

**Comment by bstifle** [comment]
@paulcpederson Just FYI for styling stuff, been seeing a lot of movement with date on another issue.

**Comment by paulcpederson** [comment]
@bstifle `master` now has most of these updates. I didn't completely hide disabled dates (ie. outside range of min/max) because it felt broken. I've used a further step down in opacity rather than completely hiding them.

If you want to give this a look over you can close if it looks good or we can address anything outstanding, but it should look like your comps for s, m, l

**Comment by bstifle** [comment]
checkin it now

**Comment by bstifle** [comment]
@paulcpederson 

![image](https://user-images.githubusercontent.com/14083530/79899649-edd04e80-83c1-11ea-89fa-35af17bb1793.png)
1. small and medium—Baseline is off on Year

![image](https://user-images.githubusercontent.com/14083530/79899789-1ce6c000-83c2-11ea-9679-a02662de223f.png)
2. min max—needs to ditch the carets if only one month is showing

![image](https://user-images.githubusercontent.com/14083530/79900703-81564f00-83c3-11ea-98e0-d5e703112cae.png)
3. Header areas—Medium is great, the vertical horizontal proportions create square caret paddles. Please increase the vertical padding/margin on small and large to keep that consistent with medium e.g. square paddles.

![image](https://user-images.githubusercontent.com/14083530/79901917-77cde680-83c5-11ea-96ad-a6a1fa3169e5.png)
4. Circle centering—somethings still off with these. i think if you made the circles odd numbers it would center properly. That, or fudge the optics .5px on the x and y. Small looks like its using 27x27 but just needs to be moved up and left 1px

![image](https://user-images.githubusercontent.com/14083530/79902140-d004e880-83c5-11ea-804b-563e39a8b3a3.png)
5. Always open—should drop the shadow and border radius, gain border-2

![image](https://user-images.githubusercontent.com/14083530/79902282-135f5700-83c6-11ea-9c6f-6c66311120f0.png)
6. Month changing—consider changing the month just like the year input. autofill if you type N or Nov, stuff like that. more of an enhancement so not a biggy

**Comment by babakbolour** [comment]
Is anyone testing these updated Styles for int'l calendars? If you know of a team that is consuming these updates, pls let me know too.
