### ISSUE TITLE
Block props and attrs

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#4460]
### Description

1. Update props and attrs for `intlCollapse` and `intlExpand` to include default values of `Expand` and `Collapse` respectively.
2. Add supporting text to support use (e.g., **aria-label for collapsing the the toggle and t**ooltip used for toggle when expanded.)

### Which Component

Block

### Resources

https://github.com/Esri/calcite-components/blob/master/src/components/block/block.tsx#L208

**Comment by benelan** [comment]
@macandcheese - when setting a prop's default value from a `resource.ts` file you need to use the `@default` jsdoc tag for it to be parsed correctly in the developer doc right? E.g. https://github.com/Esri/calcite-components/blob/master/src/components/block/block.tsx#L68

**Comment by benelan** [comment]
In my opinion having to use both the `@default` jsdoc tag and the `resource.ts` file is a bad idea because it means the value needs to be updated in two places. Maybe we shouldn't use `resource.ts` for default prop values?

**Comment by macandcheese** [comment]
Using `@default` accessible through `docsTag.default` is preferred IMO - otherwise the consumer (Docs site / storybook) needs to parse the `TEXT.whatever` as shown above, which isn't cased the same.

<img width="347" alt="Screen Shot 2022-05-09 at 10 22 25 AM" src="https://user-images.githubusercontent.com/4733155/167463771-d4ab4d56-91a4-4e5d-8813-faf216cb7b70.png">

**Comment by benelan** [comment]
I have a feeling that the doc will become out of date, because people will not remember to update the value in both locations. There isn't any way we can hardcode the value in a single place, rather than two? Like this:
```ts
 /** string to override English loading text
   */
  @Prop() intlLoading?: string = "Loading";
```
Instead of what we currently have:
```ts
 /** string to override English loading text
   * @default "Loading"
   */
  @Prop() intlLoading?: string = TEXT.loading;
```
Essentially, we shouldn't use the `resource.ts` file for props' default values. Then you wont have to parse from two places on your end too.

**Comment by benelan** [comment]
@geospatialem can you please add the `@default` jsdoc tag to these? I spoke with Franco and there is going to be refactor that changes how I18n props work moving forward so this won't be relevant after that. But until the refactor, we can keep using the `@default` tag for consistency.

**Comment by benelan** [comment]
verified on prod https://developers.arcgis.com/calcite-design-system/components/block/#component-api-properties-intlCollapse
