### ISSUE TITLE
Enhancement. Add a width prop to Switch

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#448]
Using the same pattern as Button uses.

```
/** specify the width of the switch, defaults to auto */
  @Prop({ mutable: true, reflect: true }) width: "auto" | "half" | "full" =
    "auto";
```

**Comment by macandcheese** [comment]
Is this to control the width of the switch's bounding box? 

Button seems to make sense since the rendered element takes up the desired width visibly - with the switch it's a little weird since that's just a container. We could just set it to `inline-block`, or keep it as display `block` and just let folks wrap the switch in whatever size container they want.

In the upcoming `calcite-label` component - that will function as a wrapper that provides full-width "clickability" when a switch control is placed inside (or, any other form control we have a component for). Is that what you are after here or does that not meet the needs?

**Comment by asangma** [comment]
Crap...I forgot about calcite-label.
As long as we can get this kinna layout. 👍 
![Screen Shot 2020-04-07 at 11 01 52 AM](https://user-images.githubusercontent.com/12503298/78703579-4b8f7180-78bf-11ea-8f0f-5e733e280513.png)

**Comment by asangma** [comment]
Also will this make the label and switch their own nodes so that something like this is possible?
![Screen Shot 2020-04-07 at 11 04 09 AM](https://user-images.githubusercontent.com/12503298/78703730-91e4d080-78bf-11ea-8211-35570b909c36.png)

**Comment by macandcheese** [comment]
Yep exactly, that should be achievable with: 

```
<calcite-label layout="inline-space-between">
Enable Popup
<calcite-switch></calcite-switch>
</calcite-label>
```
There's an open PR with example if you want to check out, I need to handle some spacing cases and some tests, but should be in soon.

**Comment by asangma** [comment]
Yew!
