### ISSUE TITLE
Add a "wide layout" or table layout to the card

### ISSUE THREAD

**Issue by ajturner** [Esri/calcite-components#451]
It would be useful to have a single card component support a few layout options. This way a developer or UI can just change an attribute to have the layout change. 

Similar to the AGO search results list.

**Comment by ajturner** [comment]
Similar to https://esri.github.io/hub-components/?path=/story/hub-components--hub-content-card

**Comment by macandcheese** [comment]
Yes, good enhancement. "Table" will probably have to wait until we have a better grasp on adding a true datagrid / table component, but we should absolutely add a "wide" or "horizontal" modifier to our current card in the meantime.

**Comment by macandcheese** [comment]
cc @bstifle @asangma

**Comment by asangma** [comment]
Seems legit.

Or we could have a couple different card components similar to how calcite-app-components has a couple list components.

I suggest this to reduce layout dependencies between different layouts.

If that's too weird, using CSS grid would be helpful for different layouts.

**Comment by asangma** [comment]
@ajturner I'm unclear on what a table layout would mean for a card.

**Comment by macandcheese** [comment]
> I suggest this to reduce layout dependencies between different layouts.

What do you mean by this? Just being able to add / remove a "wide" attribute when a user swaps between grid / list seems like a nice experience, rather than rendering a separate set of components (assuming the content is the same). But open to other ideas there.

I think a "table" layout should wait until we have a data grid / multiple select action bar component. That will cover a lot of UI surface.
