### ISSUE TITLE
Refactor: calcite-value-list accessibility support

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#4676]
### Discussed in https://github.com/Esri/calcite-components/discussions/4356
also cc #3982 

### Reproduction sample
https://developers.arcgis.com/calcite-design-system/components/value-list/#sample

### Discussion actions:
We plan to proceed with a `role='treegrid'` to support nesting.

#### Notes:
- [Treegrid role](https://www.w3.org/WAI/ARIA/apg/patterns/treegrid) context
- Each row will be read back to the screen reader as either expanded or collapsed (as per the `treegrid` role)
- Ensure content can be focused, as screen readers may overlook elements contained in `treegrid`. This would accommodate screen reader users who are generally in application reading mode when interacting with the grid.
- Ensure slots within the `calcite-list-item` are not keyboard navigable until the `calcite-list-item` is accessed.

#### Considerations from previous list-related feedback around a11y:

- Ensure custom controls provide proper textual name, role, and state information  
- Checked/unchecked state of the list items is announced when the item first receives focus and when the state is changed  
- Ensure the visible text label for a control is included in the control's accessible name for assistive technologies  
- Provide visual labels or instructions for user input  
- Pertaining to lists that instruct users to provide input  
- Provide a valid label for form fields  
- Pertaining to lists that instruct users to provide input  
- Avoid placing inactive elements in the focus order  
- Ensure active user interface components have sufficient contrast  
- Ensure all interactive functionality is operable with the keyboard  
- Ensure headings and labels are descriptive and unique  
    - e.g. button names “Add +”  

### Discussion context
<div type='discussions-op-text'>

<sup>Originally posted by **ffaubry** September 13, 2021</sup>
### Actual Behavior

The List keyboard navigation is not consistent with the Value List navigation.

### Expected Behavior

The value list is correctly behaving with arrow up/down moving the focus on the previous/next item. The tab is switching the focus inside the value list item and them out of the list. I think this is the correct navigation for lists.
However the current implementation for Calcite List doesn't handle the arrow up/down.

### Reproduction Steps or Sample

1. Create a List 
2. Place two List Items
3. focus on the first item
4. hit arrow down or up
5. focus doesn't change

Try the same with a Value List

</div>

**Comment by driskull** [comment]
@samanthahunter this component update has been installed.

**Comment by driskull** [comment]
BREAKING CHANGE:  To know when `calcite-list-item` content is selected, listen to the event `calciteListItemSelect` instead of `click`.

- `List`
  - Adds `label` property to specify an accessible name for the component.
  - Adds `loading` property to show a busy indicator.
  - Adds `selectionMode` and `selectionAppearance` properties to handle configuration of selection.
  - Adds `filterEnabled`, `filteredData`, `filteredItems`, `filterText`, and `filterPlaceholder` properties to support filtering.
  - Adds `calciteListFilter` event to notify when a filter has changed.
  - Deprecates `headingLevel` property.
-  `ListItemGroup`
    - Adds `disabled` property to prevent user interaction.
    - Deprecates `headingLevel` property.
- `ListItem`
  - Adds `calciteListItemSelect` event to notify when list item content is selected.
  - Adds `selected` and `value` properties to handle selection.
  - Adds `open` property to show child components.
  - Deprecates `nonInteractive` property.

**Comment by geospatialem** [comment]
Verified on `next.660` with the following [Codepen sample](https://codepen.io/geospatialem/pen/LYrvWwE).
