### ISSUE TITLE
Calcite-components-react ValueList onSelect event does not fire

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-components#5075]
### Actual Behavior

In Calcite Component react, the onSelect event does not appear to fire when we select a ValueListItem in a ValueList.  We cannot use "onClick" because we also have a dropdown menu driven by a button on the valueListItem component.

This problem is blocking needed functionality in ArcGIS Knowledge Studio

### Expected Behavior

selecting a value list item fires the onSelectEvent

### Reproduction Sample

https://codesandbox.io/s/empty-rgb-kv061e?file=/src/InvestigationContentValueListItem.js

### Reproduction Steps

1. Open the Dev tools console
2. Select any item in the value list
3. Notice that the onSelect event never triggers the bound function

### Reproduction Version

Calcite beta.86, Calcite-components-react 0.27.0

**Comment by jcfranco** [comment]
I looked at the repro case and the item selection event does fire, but under a different name (`onCalciteListItemChange`):

https://codesandbox.io/s/objective-pine-xfkfpf?file=/src/InvestigationContentValueListItem.js

The event fires when `selected` changes, so we'll probably have to revisit this separately to be consistent with other item selection components. 

TypeScript-wise, there will be an issue since there is no emitter on the list item and therefore won't have the event prop typed. I'll create a separate issue for this.

**Comment by RSantosGIS** [comment]
Understood.  I can type cast the component for now to suppress the typescript error.  I'll play around with this other event.

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/5167.
