### ISSUE TITLE
Dropdown placement/positioning wrong

### ISSUE THREAD

**Issue by daniellaumer** [Esri/calcite-components#5102]
### Actual Behavior

When placing a dropdown on the bottom of a page, sometimes the items are places below the button and therefore not visible/accessible. This only happens for some window sizes and can be best observed when changing the window height: 

![BugCalciteDropdown2](https://user-images.githubusercontent.com/93542103/183086331-c9d8c3e8-1da2-4537-9b21-0c112752a8b5.gif)

### Expected Behavior

The dropdown should be displayed on top of the button.

### Reproduction Sample

https://codepen.io/dlaumer/pen/oNqdLZm

### Reproduction Steps

1. Open the codepen example
2. Resize the height of the window (see screen gif)
3. Observe how the item list of the dropdown disappears below the button

### Reproduction Version

beta.86

### Relevant Info

Win10, Chrome

Maybe related to this issue: https://github.com/Esri/calcite-components/issues/4272

**Comment by benelan** [comment]
This works as expected if you set `placement` to "top".

```html
 <calcite-dropdown id="exampleDropdown" open placement="top">
```

**Comment by benelan** [comment]
Reopening, @daniellaumer reached out and provided another repro sample:
https://codepen.io/benesri/pen/VwXVXor?editors=1000

It is inconsistent, but open the dropdown and it is above the trigger, refresh and try again and it will eventually be below the trigger. I wasn't able to repro in `beta.86` so it may be due to the switch from popper to floating-ui

**Comment by benelan** [comment]
verified on beta.94 
https://codepen.io/benesri/pen/VwXVXor?editors=0010
