### ISSUE TITLE
Color picker: "R", "G" and "B" not flipped in RTL

### ISSUE THREAD

**Issue by C-Joubert** [Esri/calcite-components#5328]
### Actual Behavior

Hi! I'm Chris from the ArcGIS Urban team in Zurich.

(All the following screenshots were taken from https://developers.arcgis.com/calcite-design-system/components/color-picker/)

Color picker in LTR (Correct):
![Screenshot from 2022-09-15 16-49-04](https://user-images.githubusercontent.com/108517747/190436058-56e879e7-6733-4808-9b05-3d0ed39d1d35.png)

Color picker in RTL (incorrect):
![Screenshot from 2022-09-15 16-49-30](https://user-images.githubusercontent.com/108517747/190436346-247c4dd0-7b37-47d2-800c-373f03177395.png)

We found the same effect when using the color picker in our product.

### Expected Behavior

Color picker in RTL (expected behaviour, "R", "G" and "B" aligned on the right):
![Screenshot from 2022-09-15 16-50-20](https://user-images.githubusercontent.com/108517747/190436453-685630c1-9dc2-4be5-8807-fddfcaf60315.png)

Note:
On https://developers.arcgis.com/calcite-design-system/components/color-picker/, the "R", "G" and "B" flip the moment you assign a value to any of the `intl-b`/`intl-g`/`intl-r` properties.
But in when using the color picker in our product, we do supply values to the  `intl-b`/`intl-g`/`intl-r` properties and the "R", "G" and "B" and still incorrect.

### Reproduction Sample

N/A

### Reproduction Steps

Explained above, can be reproduced on https://developers.arcgis.com/calcite-design-system/components/color-picker/

### Reproduction Version

1.0.0-beta.86

**Comment by jcfranco** [comment]
@C-Joubert I can't reproduce this (see https://codepen.io/jcfranco/pen/poVRaWp?editors=1010), can you share more info about your repro case?

**Comment by C-Joubert** [comment]
Hi @jcfranco, thank you for the quick response.

Sorry, I forgot to mention that we are using it in React.
I managed to reproduce the error here:
https://codesandbox.io/s/ancient-shape-f5d738?file=/src/App.js

**Comment by C-Joubert** [comment]
I think I found the issue now. You have to specify the "dir" property directly (`dir={"rtl"}`) for the RTL to work.
If you just use `style={{direction:'rtl'}}` then you get my error.
(I've updated the repro case above)

Ok so this is a more minor bug than I thought.
If this is intended, then maybe just update the documentation that css won't be enough to flip the component, and add `dir` to the list of properties on https://developers.arcgis.com/calcite-design-system/components/color-picker/

**Comment by jcfranco** [comment]
We don't check CSS direction by design. This avoids layout thrashing when trying to use `dir` in rendering. 

I'm not sure about doc'ing this since it is not a recommended practice:

[From MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/direction#:~:text=Note%20that%20text%20direction%20is%20usually%20defined%20within%20a%20document%20(e.g.%2C%20with%20HTML%27s%20dir%20attribute)%20rather%20than%20through%20direct%20use%20of%20the%20direction%20property.):

> Note that text direction is usually defined within a document (e.g., with HTML's dir attribute) rather than through direct use of the direction property.

The W3C also [recommends against setting direction via CSS](https://www.w3.org/International/questions/qa-html-dir#no_css):

> ### Don't use CSS for direction!
> Do _not_ use CSS to apply base direction in HTML pages.
> 
> Basically, this is because you want the directional information to be available even when the CSS is not. The directional information can affect the semantics of your content, and so should be part of the markup. (See a [longer explanation](https://www.w3.org/International/questions/qa-bidi-css-markup)).
> 
> Both the CSS and HTML specs echo this same admonition.

@geospatialem @benelan I'll defer to you on that one. 🏈

**Comment by geospatialem** [comment]
> We don't check CSS direction by design. This avoids layout thrashing when trying to use `dir` in rendering.

Concur with Franco thoughts, and don't think we'd provide documentation on this since its not an industry supported approach.

We have some documentation on the [Localization page](https://developers.arcgis.com/calcite-design-system/localization/#right-to-left-rtl). 

@C-Joubert, is there some context we could add in that helps provide the context of using `dir="rtl"`? The documentation currently shows implementation for the entire application, so perhaps we could add an example in for specific components. Would that be helpful for context?

**Comment by C-Joubert** [comment]
Deaer @jcfranco and @jcfranco, thank you for the engagement and info! I appreciate it, and I definitely learned something.

> The documentation currently shows implementation for the entire application, so perhaps we could add an example in for specific components.

This is a great idea, perhaps adding to https://developers.arcgis.com/calcite-design-system/localization/#right-to-left-rtl that you can also set the `dir` property on the component itself, with an example.

![Screenshot from 2022-09-26 10-53-53](https://user-images.githubusercontent.com/108517747/192235043-4278f532-4099-406f-82cc-0264dd76412b.png)

**Comment by geospatialem** [comment]
@C-Joubert thanks for your feedback! Will add in an example in the near future, and update this issue once resolved.

**Comment by geospatialem** [comment]
Apologies for the delay on this, the [update](https://developers.arcgis.com/calcite-design-system/localization/#right-to-left-rtl) went live on October 12.

![verified rtl with component and html example](https://user-images.githubusercontent.com/5023024/202033912-c7937fca-daa6-46fb-bbd8-520a30356c23.png)
