### ISSUE TITLE
[Input] Should we translate value to different languages

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5403]
### Description

Now that we are working on getting the numberingSystem property and translation strings set up, the idea was brought up in a i18n meeting last week to translate our Input `type="text"` for consistency. 

@annierm18 can you see if this is suggested/necessary?

### Acceptance Criteria

Determine whether we need to translate our Input component's value to different languages. If we do need to translate Input's value, we can use this issue for implementation.

### Relevant Info

Just want to note that this will likely require request to a service like Google Translate. I assume any local translation packages would explode our build size.

Assuming we need to use a cloud service, translating while typing would have a serious performance impact. So if we do have to translate Input, maybe it only has to happen on blur?

FWIW, Google Translate has an NPM package:
https://github.com/googleapis/nodejs-translate

### Which Component

- Input
- Input Text

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
This seems very complex and niche. Could you also share an example demonstrating how this would work?

**Comment by benelan** [comment]
Yeah I agree I would prefer to not have to do this. It was just brought up in the translations pseudo testing meeting so I thought I'd log an issue. @anveshmekala I think you mentioned it?

I don't think it would work in terms of translating a string while typing, because it would need to send a REST request to Google Translate, or another API, for every key. It _might_ work on blur, but that's just a weird user experience to be typing in English and then the value is suddenly translated when you tab to the next input. 

Hopefully we learn this isn't necessary and we can just close the issue.

**Comment by anveshmekala** [comment]
Yup, I mentioned in the meeting regarding the number system and the outcome is that we don't translate locales with a logarithmic numbering system. Regarding Indic digits, we can explore the option but I do agree it can get complex. And the built-in translations are different because it's more of a static text rather than the user typing actively. 

I don't think `<input type="text"/>` should be translated because, in some locales, the characters can change depending on the next character that will be typed so we may have to re-run the translation for the whole string rather than just the character. 

And translating the strings while the user is typing ( assuming the user's keyboard is different from the requested locale) would be expensive. Even if we could find an npm package with the right build size, would converting strings provide a good UX is something we need to discuss.

**Comment by benelan** [comment]
Oh okay I must of misunderstood during the meeting. It sounds like no one thinks we should support translating input type="text" so I'm going to close this issue

**Comment by benelan** [comment]
> we don't translate locales with a logarithmic numbering system. Regarding Indic digits, we can explore the option but I do agree it can get complex.

FWIW I have indic digits working in a codepen. I should have a PR soonish
https://codepen.io/benesri/pen/XWqYzrP?editors=0010

It only supports the `numberingSystem`s supported by `Intl.NumberFormat`, which are listed here
![image](https://user-images.githubusercontent.com/10986395/193912865-3858febe-44b6-4ee3-9681-7effee687616.png)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters

None of those are algorithmic.
