### ISSUE TITLE
calcite-button focus look too bold

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#555]
focused calcite-button has a scary look.

<img src=https://user-images.githubusercontent.com/44481292/81094691-bd57dc80-8eb8-11ea-9b0e-d16d67547ab1.png width=200/><img src=https://user-images.githubusercontent.com/44481292/81094903-10ca2a80-8eb9-11ea-831e-18d4903513bb.png width=200/>

cc @asangma

**Comment by macandcheese** [comment]
cc @bstifle @asangma - I think it's a combination of not having a rounded focus style yet, PLUS it being floating...

**Comment by AdelheidF** [comment]
Not floating in this particular case.

**Comment by asangma** [comment]
@macandcheese @AdelheidF Are we talking about the border thickening on focus?

**Comment by AdelheidF** [comment]
> Are we talking about the border thickening on focus?

For me it's the whole look. If you want to stick with a 2px focus border that's fine, but together with the thick button oval it's too much.

**Comment by macandcheese** [comment]
It looks like there's a box-shadow there from 'floating' (maybe my eyes are playing tricks on me). Agree, it's kind of heavy-handed focus styling in general but... I think that's the direction that gives us the most coverage for audits and usability. Open to changes of course - not sure if having this be "rounded" focus vs. the square would help in this case...

**Comment by macandcheese** [comment]
I don't think we'd change the focus style at this time - in the example above it certainly seems like there is a shadow from `floating` that makes it a little heavier as well. Without `floating` its a little better although still pretty heavy:

<img width="320" alt="Screen Shot 2020-07-23 at 12 40 27 PM" src="https://user-images.githubusercontent.com/4733155/88331388-b97e6e00-cce1-11ea-937b-844fe779c7a6.png">

We have thought about adding more focus styles for rounded elements but its hard with a mixin since that could not use `outline` and instead would need to accept any existing `box-shadow` values...
