### ISSUE TITLE
Where is CDN \ ADM release for 1.0.0-beta.97

### ISSUE THREAD

**Issue by capegreg** [Esri/calcite-components#5667]
### Description

Where is 97
https://js.arcgis.com/calcite-components/1.0.0-beta.95/calcite.js

### Which Component

https://github.com/Esri/calcite-components/releases

**Comment by benelan** [comment]
Hi @capegreg,

The ES5 build was removed, since we only [support the latest 2 versions of the major browsers](https://developers.arcgis.com/calcite-design-system/system-requirements/). ES6 is widely supported, so your users shouldn't run into any issues. [Here are the browser versions that support ES6](https://caniuse.com/?search=es6).

This means you no longer need to include the `nomodule` CDN script, you only need these two:

```html
<script type="module" src="https://js.arcgis.com/calcite-components/1.0.0-beta.97/calcite.esm.js"></script>
<link rel="stylesheet" type="text/css" href="https://js.arcgis.com/calcite-components/1.0.0-beta.97/calcite.css" />
```

Sorry, we [tried to add the removal](https://github.com/Esri/calcite-components/pull/5469) to the changelog's breaking changes, but it must have been overwritten by the CI. I just added it back now. Thanks for reporting!

**Comment by capegreg** [comment]
Thanks, do you have the non-esm CDN?

**Comment by benelan** [comment]
The ES6 build was completely removed, so the non-ESM CDN is no longer generated. Is there a reason why you need it?

If it's a deal breaker for you, you could build the components from source and copy the CDN to your app. But it isn't necessary unless you specifically know your users are stuck on really old browsers.

**Comment by capegreg** [comment]
Ben, my framework is Wordpress, so I cannot use esm because adding calcite reference in PHP throws error.

Please see reply from ReneRubalcava.
https://community.esri.com/t5/arcgis-api-for-javascript-questions/cannot-use-import-statement-outside-a-module/m-p/1186344#M77768

**Comment by benelan** [comment]
Interesting, thanks for the use case. I will look into this. In the meantime, here are the steps for generating the non-ESM CDN file. 

```bash
git clone https://github.com/Esri/calcite-components.git
cd calcite-components

# checkout the tag for the release you need
git checkout v1.0.0-beta.97

# revert the es5 build removal, may cause merge conflicts
# https://github.com/Esri/calcite-components/pull/5412
git revert 80dba61e577fa5a33a756de0b62cbb235317f07d

# install deps and build
npm install
# may run into type errors on the first build in a fresh clone
# due to a stencil bug: https://github.com/ionic-team/stencil/issues/3239
# if you do, try to build again
npm run build

# copy the file to your app
cp ./dist/calcite/calcite.js "$CALCITE_APP_PATH/calcite.js"
```

**Comment by benelan** [comment]
It looks like Wordpress may actually support ESM with a bit of configuration, e.g.
https://stackoverflow.com/questions/62553169/importing-node-modules-in-a-wordpress-plugin

That would probably be easier than building from source after every release.

**Comment by capegreg** [comment]
Yes, I was looking at this exact post. I'm trying it now. Thanks, Ben. My plan is to  eventually transition to TypeScript and create a widget for my MapView, so I would love to get the ESM method working. Though this is a major showstopper for our release. We're 2 weeks away from release and I was already watching a calcite bug to be fixed ([slider](https://github.com/Esri/calcite-components/issues/5382) for it. When was the plan to end non-ESM builds? Was it already part of the calcite development life cycle phase? I'm not sure how I would have missed that.

**Comment by benelan** [comment]
If you plan on using TypeScript, you will probably need to use the Calcite NPM package, rather than the CDN. I did some quick googling, and [this may be worth looking into](https://developer.wordpress.org/block-editor/how-to-guides/javascript/js-build-setup/) as well. They mention ES Next, which is well past ES6.

The ES5 build hasn't been officially supported for some time, since the last 2 versions of browsers have supported ES6 for a while now. It was mostly kept around to give users time to transition. We also did ask for feedback in the PR, and added it to the "Unreleased" changelog section after installing. But unfortunately it was removed from the changelog at the time of the beta.97 release (added back now). 

Do you have any suggestions for how we can do a better job of messaging breaking changes out to the community? One thing we could do is make Esri Community posts for these kind of announcements, would that help?

**Comment by capegreg** [comment]
The script_loader_tag solution worked out. Thanks! I can't think of any suggestions. I will just do a better job at keeping up with the changelog and discussions. 


![image](https://user-images.githubusercontent.com/1051118/199238330-f44d8882-077f-4de6-8b9a-db294bbde79a.png)

**Comment by capegreg** [comment]
The script_loader_tag solution worked out. Thanks! I can't think of any suggestions. I will just do a better job at keeping up with the changelog and discussions. 


![image](https://user-images.githubusercontent.com/1051118/199238330-f44d8882-077f-4de6-8b9a-db294bbde79a.png)
