### ISSUE TITLE
calcite-alert: auto-dismissable and immediately open without JS

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/calcite-components#570]
Is there a way to be able to have a `<calcite-alert>` that's both `auto-dismiss="true"` and opened immediately (or added to the queue immediately), _without_ any need to get a JS instance reference to the component and call `myInstance.open()`?

The use case I have is not necessarily being able to gain any access via JS to the component instance to call `.open()` on it (for example in a Svelte's "each" block template helper), but as soon as I add the component to the DOM I want it to be opened (or added the queue).

I've found that simply setting `active` to true will open the alert as desired; however, it will interfere with the auto-dismiss timer and keep it open.

Repro:
<https://esri.github.io/calcite-components/?path=/story/alert--alert-title-message-link>
1. auto-dismiss, check ON
2. active, check ON
3. note that it doesn't go away when the auto-dismiss timer is complete
    - my assumption is that `active` is blocking it (by design or otherwise)

Hopes & dreams:
1. auto-dismiss, check ON
2. active, check OFF (if I understand the purpose of this property)
3. be able to have it open immediately without JS methods
4. goes away when the auto-dismiss timer is complete

**Comment by macandcheese** [comment]
Yeah, looks like the `active` in DOM is keeping it open, will look into solving. PRs always welcome 😉

**Comment by jwasilgeo** [comment]
Are you thinking that having `active` true and `auto-dismiss` true is valid for 1 alert or multiple alerts in a queue, and that `active` should not block the currently visible alert from closing after the dismissal timer is finished?

**Comment by macandcheese** [comment]
If multiple are added to the DOM with active set they (currently) won't check to see if they should queue or display, so they'll stack (not queue), which we don't want. 

When it's added we can check for other active alerts - if there aren't any, show the new one, if there are, add it to the queue. I think the active attribute on subsequent ones added to the queue would be removed from DOM since ones it's in the queue the events look for "next up" to set active programmatically (if I'm understanding the q, ha).

Re: dismissing, yes just need to make sure auto dismiss removes the active from DOM - I think the use case you had makes sense, it was just overlooked when building, since they were expected to have open called on them.

**Comment by macandcheese** [comment]
@jwasilgeo give this a check on master when you get a chance
