### ISSUE TITLE
Dark/Light button colors incongruous with dark/light mode

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#576]
A button set to `color=dark` works well on the light mode foreground, but less well on the dark mode foreground. The opposite true when a button is set to `color=light`. This is primarily an issue with the transparent button but can also be seen with other button appearances.

![Screen Shot 2020-05-08 at 2 30 21 PM](https://user-images.githubusercontent.com/15875886/81451040-7841dd80-9138-11ea-935c-4a342609edb5.png)

Suggestion:
- `color=neutral` = dark text in light mode, light text in dark mode. Allows the button to always work when sitting on the foreground color.
- `color=inverted` = light text in light mode, dark text in dark mode. Allows the button to sit on non standard background colors.

**Comment by macandcheese** [comment]
cc @bstifle 

Recommend we see what others do here - I agree the naming could be updated.

**Comment by macandcheese** [comment]
It's a weird scenario we tried to avoid where you may be requesting a "dark" button in "dark" theme, and get a "light" button - by just leaving the intended colors as such, but I think it should be updated in some way... seems like it applies to "transparent" and "clear" appearance variants because those two do not have a background - "solid" and "outline" work as intended. If we we were to change the "light" and "dark" color nomenclature that would probably need to affect all variants.

**Comment by bstifle** [comment]
Let's jump on this!

I like `neutral` and `inverted`


![image](https://user-images.githubusercontent.com/14083530/97036268-31e90b00-152d-11eb-9c58-bceb9c367ac2.png)

**Comment by crowjonah** [comment]
As part of this work, we'll wanna make sure the `calcite-split-button`'s separator elements (border, background, and divider) match the color updates made here. (See https://github.com/Esri/calcite-components/pull/1141 for some background/context.)
