### ISSUE TITLE
calcite-value-list unintentional spacing between calcite-value-list-items

### ISSUE THREAD

**Issue by jonas-dp** [Esri/calcite-components#5765]
### Actual Behavior

There is a really small space between the second and third calcite-value-list-item, which does not occur between other items.
![image](https://user-images.githubusercontent.com/20268990/202129275-1e8817d2-7c22-41a4-abbc-002cedf7d1e1.png)

### Expected Behavior

No spacing between the second and third item.

### Reproduction Sample

https://codepen.io/jonasdepelsmaeker/pen/ExRvMGV

### Reproduction Steps

1. Create a calcite-value-list
2. Add some calcite-value-list-items to the calcite-value-list
3. Observe the spacing between the second and third item in the list

### Reproduction Version

1.0.0-beta.95

### Relevant Info

WIndows 10, Chrome 107

### Esri team

N/A

**Comment by geospatialem** [comment]
With the `value-list` deprecation, we recommend folks migrate to the `list` component. Since parity will be met in the near future, some bugs that don't have a large impact will be closed in favor of the refactor work on `list`.

Final parity of the `list` component will be carried out in 2023, where progress can be followed via https://github.com/Esri/calcite-components/issues/6430.
