### ISSUE TITLE
[Research] Visual testing

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#577]
Look into using Percy, Browserstack, something of that sort for visual testing...  Maybe (?) at PR-time as a check integrated with GH?

cc @eriklharper @julio8a

**Comment by eriklharper** [comment]
Saw at least some promise using Stencil's E2E screenshot method outlined here: https://stenciljs.com/docs/screenshot-visual-diff but to scale that approach would require a bit of behind-the-scenes work of making sure that captured visual screenshots can be stored somewhere scalable, like an S3 bucket like how Ionic does for their own screenshot tests.

If we can get the budget approval for it, an automated service is the way to go for something like this.  I've used both Screener.io and Percy.io for many years, and both are amazing, capable tools.

**Comment by julio8a** [comment]
@Esri/calcite-components 

We're looking at adding a visual automation testing tool for our components, this will drastically help with QA and not having things break visually without notice. 

We are between two candidates at the moment and would like your input.

- [Percy](https://percy.io/)
- [Screener](https://screener.io/)

Please review the two and provide some feedback by 5/20

**Comment by jcfranco** [comment]
Just from a quick glance, my vote is on Screener since they support Chrome, Firefox & IE11 (Percy only supports the first two) and they also integrate with Storybook component stories.

**Comment by eriklharper** [comment]
+1 for Screener.  Used both Screener and Percy, and Screener is by far and away the more robust option.

**Comment by paulcpederson** [comment]
> Do you use Storybook to develop your UI components? Screener automatically pulls component states from Storybook, and uses them as visual test cases for automated visual testing; no coding required.

Looks like screener also has a nifty integration with storybook, so we could just use our storybook as the test cases, maybe?

**Comment by eriklharper** [comment]
@paulcpederson There's certainly a possibility that Storybook could accomplish a decent amount of test cases, since it allows you to do e2e type stuff from in Storybook's stories.js files.

At Meridian, my last job, this was all the testing we did with our components, we didn't really write any traditional unit tests, but I do think that there could be some cases where we might need to write a traditional e2e test.

I'm thinking of the radio button component I just built and in order to test that it keeps track of the hidden `<input type="radio">` node I really had to write a full e2e test to check for it in the DOM when the button was added, moved or removed.  I _think_ I could do this with Screener/Storybook, but I'd have to look into that more.

The way I usually look at screenshot testing services like these is that they serve a supplemental role to other tests that you might have, and provide a super-valuable laser-focused eye on visual changes that cascade across the whole component library, so they can catch bugs that many unit or e2e tests wouldn't simply because they literally take pictures of every story.

One caveat to really getting the most value out of this is to balance the need to have Storybook be both a "playground" for other developers to tweak knobs and see the result on the screen, but also be a visual testing environment.  The stories themselves would need to be beefed up to add all the steps necessary to visually test each component, otherwise we could be missing opportunities to catch some visual regressions, such as hidden things like modals or dropdowns that need to be clicked to open.

**Comment by eriklharper** [comment]
I inquired with Loyal who is the main contact I've had with Screener.io in the past.  Here's our recent convo where I asked him about web component support with Screener.io:

```
Hey Erik, screenshots and interactions should be fine. The difference is that Screener does a "hybrid" diff - it looks at both the screenshot image and the DOM to perform its comparison, and then it provides additional change details based on the DOM - even showing code/style differences. Its the DOM comparison that does not fully support shadow-dom.

Loyal from Sauce Labs
Powered by Intercom | Powered by Intercom
Powered by Intercom

On Thu, May 21, 2020 at 08:24 AM, "Erik Harper" <eriklharper@gmail.com> wrote:

Yes, a lot of them do in fact. I'm curious what elements of shadow dom would not be supported because at the end of the day they're just components like other frameworks, they produce UI in the browser from interactions. Curious to learn more about that.

Thanks!
Erik

On Wed, May 20, 2020 at 09:50 PM, "Loyal Chow" <loyal.chow@sauce-labs-0c200743c29e.intercom-mail.com> wrote:

Hi Erik, good to hear from you! Sorry for the late reply - Screener's Intercom is no longer monitored regularly, as we've switched our support channels to Sauce Labs.  To your question, Screener support Storybook - but Screener does not yet fully support shadow-dom. I'm assuming your web components are based on shadow-dom - is that correct?

On Tue, May 12, 2020 at 02:49 PM, "Erik Harper" <eriklharper@gmail.com> wrote:

Hi Loyal! This is Erik, you would remember me from Meridian/Aruba/HPE. I work for Esri now and we're exploring a screenshot testing tool for our Calcite Design System written with StencilJS.

Since Stencil is just a web component compiler, and we also use storybook, I wanted to see if Screener officially and fully supports this way of authoring components in all of its APIs, including in particular the Steps API that I am so fond of from back when we used Screener to test dropdowns and stuff.

I find a big differentiator between Screener and something like Percy, which as you know I have some experience with as well is these deeper interaction features like Steps and the like. Would love for you to speak to that so I can bring that info to my team who are considering it.

Thanks!--Erik Harper

```

**Comment by macandcheese** [comment]
Seems like the screenshot diffs should be enough to capture discrepancies vs. needing the tool to compare the shadow DOM. I think a PR / CI step for running these kinds of tests would be the most painless - although I think a sticking point would be the workflow of "who logs in to Screener to verify the changes are acceptable" and the associated account cost with that. Maybe a conversation for Teams 🧑‍🤝‍🧑👪

**Comment by eriklharper** [comment]
@macandcheese agreed.  I've successfully used Screener at PR time and it works very good.

As to your question about approvals, that is a good topic to discuss.  On the small team I used this tool with, us front end developers did the approvals on our own as part of standard code review, but since this team is much larger and we have lots of dedicated design resources, we could consider adopting an approach that involves design team members getting notifications of screenshot diffs as part of the design approval PR process.

The trick will be managing the notifications so that there aren't a barrage of unnecessary "in progress" screenshot test runs, which is what does happen when you have a screenshot CI step that runs on each commit on an open pull request.

This is one of those things that can be adjusted as needed once it is put into live use, in fact that's a good expectation to have with adopting a new tool like this.

**Comment by julio8a** [comment]
Need to follow up on this.

**Comment by eriklharper** [comment]
I meant to update this thread with the latest information I received from Loyal at Sauce Labs.  Because the convo is quite long, I'll summarize it by saying that it sounds like Screener.io won't be able to support our Stencil components until they can build in shadow DOM support into their diffing procedure.  Because they rely on a hybrid diff, which is DOM + Visual Screenshots, Loyal is saying that they have to build support in for Shadow DOM. 

He last wrote this to me after I asked him about ways we can use Storybook Knobs to produce screenshot diffs rather than update our stories to show all possible UI states for each component.

> Thanks for the feedback Erik!

> As for Shadow DOM support, this is necessary for the diff to work - we do a hybrid diff (screenshot and dom). Once that's in place, then Screener Runner sounds like it can provide what you need to get started.

> Thanks,
> Loyal

From what he described to me, we wouldn't go the route of using Storybook stories to do the screenshot diffing since we rely on knobs for people to use it as a playground and Screener doesn't provide an easy integration to turn on/off knobs when taking screenshots to test.  The alternative is to use Screener Runner on our demo pages, for example, which would screenshot "kitchen sink" examples for each component, which gives us a lot more confidence with visual changes since we can capture every possible UI state that we want to track when we make changes.

But, unfortunately it sounds like without the shadow DOM support aforementioned, we won't really be able to proceed with Screener for calcite.  A tool like Percy _should_ work since I know it doesn't rely on a "hybrid" diff, so we should take that into consideration moving forward.

Loyal did give me a ballpark timeframe for when they will be adding shadow support:

>Hi Erik, FYI: we are actively working to support shadow dom, and hope to have a release early Q3 - integrated with our hybrid diff, RCA details, storybook/steps API, etc.

I also heard that purchasing is on hold, so that's a blocker anyway to adopting a new tool.

**Comment by paulcpederson** [comment]
Wondering if we can just wait for full stencil's visual diffing functionality to land? It's experimental right now.

https://stenciljs.com/docs/screenshot-visual-diff

**Comment by eriklharper** [comment]
I've explored that and it would take a lot of work on our part to set that up and maintain it.  We would need a CDN to store screenshot images, since Github has size limits for repos.

**Comment by eriklharper** [comment]
Good news!  Got this response today from my contact at Screener.io:

> Hi Erik,
> 
> Thanks for reaching out and good to hear from you - Shadow DOM support is progressing well, and we plan to release for Screener Components in the next few weeks.
> 
> I will keep you posted when this out and available for you to try, thanks Erik,
> 
> Loyal
