### ISSUE TITLE
[Research] Revisit click/focus behavior of <calcite-label> children

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#581]
`<calcite-label>` has issues supporting focus behavior when wrapping `calcite-radio-button-group` due to the fact that `calcite-radio-button` renders a native `<input type="radio">` element for browser-default focus and keyboard behavior.

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-label/calcite-label.tsx#L149-L151

☝️ We might want to revisit the need for this kind of behavior and/or consider modifying things to accommodate the `<input type="radio">` elements used by `calcite-radio-button` in order to allow this kind of focus behavior (if needed).

**Comment by macandcheese** [comment]
Yep - agreed. I think a better thing to do is probably just listen for the label's focus event in each child that has a specific need (switch, slider, radio group, etc.), and handle the focus in the child component rather than label. I have an open issue to make those changes - https://github.com/Esri/calcite-components/issues/481

It's also more sustainable for each "new" control element to just be able to listen for an event and handle itself, than update label every time.

**Comment by macandcheese** [comment]
It's looking for "input" vs. "calcite-input" in order to handle native inputs wrapped in a `calcite-input`, but maybe that's not something we need to handle?

**Comment by macandcheese** [comment]
@eriklharper I am planning on changing this to emit a `calciteLabelFocus` event, which any child component can listen for in their own `handleLabelFocus` function and act as they need to when received. The only focus handling I plan to leave in `calcite-label` is when an input is specifically requested with `for`, or there's a wrapped `input` or `textarea` element inside to focus. All control elements (radio group / radio button / slider / checkbox / toggle / etc) can listen for the new `calciteLabelFocus` event. I'll try to update all in the PR.
