### ISSUE TITLE
Add mobile responsiveness to stepper

### ISSUE THREAD

**Issue by amandathomas-90** [Esri/calcite-components#599]
We need mobile responsiveness for the [stepper](https://esri.github.io/calcite-components/?path=/story/stepper--no-content) so that we can start using it in some upcoming designs.

**Comment by macandcheese** [comment]
Thanks for opening - this is a tough one, mostly because different apps will all have different desired breakpoints for when something should adjust it's design.

A longer term solution might be to allow "theme" overrides to provide a S, M, L breakpoint pixel value - right now I believe only Alert and Modal "respond" and those use fixed values.

Short term, we do have a 'layout=vertical' option for stepper which could work, but slightly changes how it functions (content is wrapped in step).

Would the desired design for 'layout=horizontal" in "mobile" just have full width "step toggles"? That would be easy enough to add using our current breakpoints for Alert, Modal.

Thanks!

**Comment by macandcheese** [comment]
An option would be to just break to full-width for "horizontal" layout mode ("vertical" works as is on mobile due to its layout, but renders step content _inside_ the step rather than in a consistent area beneath, so the function is a bit different)... Not the greatest solution without allowing folks to choose their preferred breakpoints... but would this work for now? Maybe 50% width and then 100%

Any thoughts @bstifle 

<img width="500" alt="Screen Shot 2020-05-20 at 11 30 45 AM" src="https://user-images.githubusercontent.com/4733155/82483585-7a3b6300-9a8d-11ea-9c2f-25c7aac9944f.png">

**Comment by amandathomas-90** [comment]
Hi Adam, thanks for your quick response on this. I've been working on mocking the vertical mode in my designs to see if it can work well for my current project. It's helpful to know that we can have content appear below the steppers. That was my main concern with the vertical mode as I'm trying to fit a fair amount of content into these steps. Is this 100% "horizontal" layout mode feasible in a modal? That's where my stepper would be for this project.

**Comment by macandcheese** [comment]
Hey @amandathomas-90 - Sure, currently you can position a "horizontal" layout within modal content - however it might be a good addition for us to add a specific "modal-stepper" slot that positioned the stepper above the "header / content border" - this is a use case we've seen a lot and currently there is some extra padding associated with just placing a stepper inside the modal content area.

Re: switching to "vertical" layout - currently that would be up to the application to detect a certain px width breakpoint and make the switch via prop.
