### ISSUE TITLE
Refactor event payload for consistency

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6007]
### Description

The following list of events could have their payloads deprecated`*`, or cleaned up for consistency. cc @driskull 

Note (`*`) : For those where the event payload could be removed, some may require introducing a public property.

- [x] `calciteComboboxFilterChange` - @driskull 
- [x] `calciteComboboxChange` - @driskull 
- [x]  `calciteDatePickerChange`  - @driskull 
- [x] `calciteDatePickerRangeChange` - @driskull 
- [x] `calciteDropdownSelect` - @driskull 
- [x] `calciteRatingChange` - @driskull 
- [x] `calciteTabChange` - @driskull 
- [x] `calciteTreeSelect` - @driskull 
- [x] `calcitePaginationChange` - @driskull 
- [x] `calciteDatePickerActiveDateChange` - @driskull
- [x] `calciteDatePickerSelect` - @driskull
- [x] `calciteRadioGroupChange` - @driskull 
- [x] `calciteTabsActivate` - @driskull 
- [ ] `calciteListChange`. (PickList/ValueList) - TBD
- [ ] `calciteListOrderChange` (PickList/ValueList)  - TBD

### Proposed Advantages

For consistency across components prior to the January release.

### Which Component

- combobox
- date-picker
- dropdown
- list
- pagination
- radio-group
- rating
- tab
- tabs
- tree

### Relevant Info

An audit was conducted to determine the events sought for event payload deprecation or clean up. Visit https://github.com/Esri/calcite-components/issues/2925#issuecomment-1349503060 for details.

**Comment by driskull** [comment]
@eriklharper @benelan @geospatialem in regards to removing `event.detail` from some events...

These events are on the DatePickerMonth/DatePickerMonthHeader. Do we need to document these or can we just mark them internal? These components aren't designed to be used on their own.

- `calciteDatePickerSelect` - DatePickerMonth/DatePickerMonthHeader
- `calciteDatePickerActiveDateChange` - DatePickerMonthHeader

These are on the ValueList/PickList. Should we modify them or just let them be since we will likely deprecate them?

- `calciteListChange`
- `calciteListOrderChange`

My vote would be to deprecate the list events and mark the datepicker ones as internal. Thoughts?

**Comment by anveshmekala** [comment]
I agree with marking datepicker ones as `@internal` and deprecating the valueList/pickList related events considering the components will be deprecated.

**Comment by benelan** [comment]
Yup agree on both points

**Comment by driskull** [comment]
I left the list events alone, we can decide to update them later if we want.

**Comment by geospatialem** [comment]
The `calciteDatePickerSelect` and `calciteDatePickerActiveDateChange` are confirmed as internal events.

The remaining events are confirmed to no longer have `event.detail` for their event payload (with the exception of the two list events, `calciteListChange` and `calciteListOrderChange`.

**Comment by anveshmekala** [comment]
Can we add `calciteInputTimePickerChange` to the list?
