### ISSUE TITLE
after sorting blocks a list within a block no longer sorts

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#6024]
### Actual Behavior

I have a sortable list of blocks and some of them contain a sortable list. All is well until you re-order the blocks, then the inner list no longer sorts.

### Expected Behavior

sorting keeps working

### Reproduction Sample

https://codepen.io/afreitag/pen/eYKweaz

### Reproduction Steps

1. sort inner list, Food, Rend... - works
2. move block B below block C
3. sorting inner list no longer works

### Reproduction Version

beta.98

### Regression?

don't think so

### Impact

moderate-high

### Esri team

ArcGIS Map Viewer

**Comment by lau11123** [comment]
cc @driskull for when he's back.

@geospatialem is there any status on this? Can a milestone be set please?

**Comment by geospatialem** [comment]
@lau11123 Apologies for the lack of communication, we'll be prioritizing issues after this month's release for inclusion in upcoming releases. Will post an update once we're able to assign a milestone in a few weeks.

**Comment by lau11123** [comment]
@geospatialem thanks!

**Comment by geospatialem** [comment]
Additional research and follow-up needed pertaining to the `list` component sorting in 2023.

**Comment by driskull** [comment]
The problem lies with the `sortable-list` component.  It's `handleSelector` is set to `calcite-handle` which also targets the `value-list`'s calcite-handle. The `handleSelector` prop isn't very useful because you can't target within a specific shadowRoot of a component.

If the `calcite-block` allowed you to slot a handle instead of just adding it for you inside the shadowRoot then this would be doable as you could update the sortable list to only target specific handle elements.

**Comment by geospatialem** [comment]
Verified on `master`.

![verify-6024](https://github.com/Esri/calcite-components/assets/5023024/4e462184-5d08-4c96-8a48-a0041d6a557b)
