### ISSUE TITLE
Custom border radius

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#606]
Would it be possible to expose a CSS variable to customize the border-radius of the components?

We personally would need it for `calcite-button` and `calcite-input`. We managed to do it for the `calcite-input`, but the CSS additions are directly tied to the inner component structure, which could change on your side for some architecture reason, making our trick ineffective. 
To give an idea about the `calcite-input` type "number", with a `0.2rem` `border-radius`:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/45367780/82402057-56860780-9a10-11ea-9d4a-613f0edbd50a.png">

```css
@mixin calcite-input-number {
  > div {
    > input[type="number"] {
      border-radius: var(--arcgis-charts-border-radius) 0 0 var(--arcgis-charts-border-radius);
    }
    > div {
      > div[data-adjustment="up"] {
        border-radius: 0 var(--arcgis-charts-border-radius) 0 0;
      }
      > div[data-adjustment="down"] {
        border-radius: 0 0 var(--arcgis-charts-border-radius) 0;
      }
    }
  }
}
```

The `calcite-button` has an interesting "round" style, but it seems like the 50px border-radius cannot be changed.

Thanks!

**Comment by macandcheese** [comment]
Hi @pemberdom - at this point - no. In the future we may expose these as overrides. We would need to accept two values:

`--calcite-ui-border-radius-1` (currently in Calcite Components, this = `0`)
and
`--calcite-ui-border-radius-2` (currently in Calcite Components, this = `3px`)

This is because for certain "floating" components (alert, modal, tooltip, popover, etc.) use the `-2` value, and we want to continue to enforce that.

**Comment by macandcheese** [comment]
A concern we have with overrides is applications ensuring to add the reciprocal RTL styles... in the example above we'd also want to make sure that the "floating" components had a significantly higher border-radius. A multiple of `--calcite-ui-border-radius-1` would work for cases where it wasn't set to `0`...

**Comment by pemberdom** [comment]
I don't fully understand the different implications about RTL and floating (I trust you on this 😄), but is it different from the actual behavior implemented for the "round" button?
That 50px value is hard-coded if I'm correct, would exposing it as a variable create potentially the issues you're mentionning?

**Comment by macandcheese** [comment]
Hey - yeah, `rounded` button variant would likely stay hardcoded (since it's essentially a prop for "display this button as a pill", so to override that to be ... not a pill would be a little weird), but if we were to expose the underlying border radius as a css variable teams could override the two values and essentially achieve a button like you describe. Maybe we'd then need to change that prop name to "pill" or something, I've seen that terminology used.

Floating just was a term for our UI elements that are positioned "above" the page surface - we apply a box shadow and border-radius to these and would like to keep that consistent - so if a team were to change `--calcite-ui-border-radius-1` (should we add that) to `2px`, we'd prefer floating elements to increase as a consistent clip.

For RTL, in your overrides, I just meant you'd need to reciprocally apply the border-radius when those buttons are positioned on the left side of the input in RTL :)

**Comment by pemberdom** [comment]
We have to fix our custom borders for RTL indeed!
Thanks for the explanation 👍!

**Comment by macandcheese** [comment]
At this point we won't be adding custom border radius.. Closing for now!
