### ISSUE TITLE
Radio Group: Update Appearance property to be consistent with changes

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6095]
### Description

We missed the Radio Group with the recent Appearance changes, it's still using `minimal` as a value but should be using `outline`:

![image](https://user-images.githubusercontent.com/4733155/208227043-50e987ef-ca0c-46df-872a-82fc835ed784.png)

cc @ashetland @SkyeSeitz @geospatialem 

### Acceptance Criteria

Updates Radio Group to use "outline". The component currently has a bg applied to the active item, so that should probably be transparent to truly match the meaning of "outline"

### Relevant Info
I guess looking at this should this be outline-fill with a different variant for outline - transparent bg and filled radio item or something? @ashetland @SkyeSeitz

**Comment by macandcheese** [comment]
Installed in https://github.com/Esri/calcite-components/pull/6096, if we do determine we want to add the extra variant we can safely do so as it won’t be a breaking change.

**Comment by ashetland** [comment]
Since the appearance prop is set on the group, this update would bring it inline with the others.
- rename `outline` appearance to `outline-fill`
- add new `outline` variant that removes the bg color

![CleanShot 2022-12-19 at 08 56 16@2x](https://user-images.githubusercontent.com/108549080/208480109-87465558-7906-49a7-9701-fefe37d85856.png)

**Comment by geospatialem** [comment]
Verified in `beta.99`.

![image](https://user-images.githubusercontent.com/5023024/209978579-fdc65f9b-698a-48cb-97b4-e2bad7d926f0.png)
