### ISSUE TITLE
Hovering over the calcite alert when saving a map will not automatically dismiss

### ISSUE THREAD

**Issue by rebollin** [Esri/calcite-components#6222]
### Description

The final calcite alert for saving in Map Viewer will not automatically dismiss after a certain allotment of time. This seems to happen after the user hovers over the previous notifications. Talked with @geospatialem and it is likely a result of this PR https://github.com/Esri/calcite-components/pull/5872. Here is a codepen for this issue: https://codepen.io/kevindoshier/pen/ZEjQPjB

![savefreezing](https://user-images.githubusercontent.com/121894974/210432869-d3ade707-76c0-47f1-a528-ddea1eb55ca6.gif)

### Acceptance Criteria

The alert should automatically dismiss after the allotted time rather than having the user manually close it.

### Which Component

alert component 

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Could see a use case for potentially having the alert not dismiss automatically when pausing due to hovering (and eventually focusing via #5960). 

Should we consider introducing a boolean property to handle both use cases?

Will evaluate prioritization after this month's 1.0 release for a future milestone and/or assignment.

**Comment by macandcheese** [comment]
I think we should prioritize the bug fix for 1.0, if we can.

> Could see a use case for potentially having the alert not dismiss automatically when pausing due to hovering (and eventually focusing via https://github.com/Esri/calcite-components/issues/5960).

I think this would just be a use case to not have the auto-dismiss property enabled at all by an app. I would expect the dismiss timer to resume once hover / focus leaves, I feel like having an option to "leave the timer halfway done" is kind of strange?

There is precedent for a `no-hover-pause` property: (https://bootstrap-vue.org/docs/components/toast#comp-ref-b-toast-props), but slightly unrelated I suppose.

**Comment by geospatialem** [comment]
Adding to the January milestone, if time permits from the team to tackle.

**Comment by macandcheese** [comment]
Somewhat separately from the component but, looking again at the gif provided, I think invoking the “saving” alert, then removing it without user interaction to replace it with another “save complete” alert is a bit of a weird experience, and might feel broken to a user.

Alternatively, a loading state / loading spinner could be used on the folder action in the action bar instead of the initial “saving” alert - then just provide a single success alert.

**Comment by macandcheese** [comment]
@rebollin @kevindoshier this should be available to test on next release if you could give a look and test it out :)

Would also recommend the UX suggestion above be implemented, check with @asangma for interaction details there.

**Comment by geospatialem** [comment]
Verified on `next.710`. 
![verify-alert-auto-close](https://user-images.githubusercontent.com/5023024/210896705-4d4331cb-d737-450f-84be-3c6465337616.gif)

**Comment by rebollin** [comment]
This looks good on MV now after the latest update
