### ISSUE TITLE
Calcite-Select > Toggling disabled changes selected item

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-components#6231]
### Actual Behavior

When calcite-select is enabled it appears that the selected index is changed (permanently) to the original value.
![2023-01-04_11-07-58](https://user-images.githubusercontent.com/2531121/210631181-c671bbdf-61e1-421a-8419-ab9062506a57.gif)

### Expected Behavior

Toggling disabled should not change the component's selected value.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/select/

### Reproduction Steps

1. Open https://developers.arcgis.com/calcite-design-system/components/select/
2. Pick Lakes
3. Check disabled
   - Selected item reverts to Manufacturing

### Reproduction Version

1.0.0-beta.99

### Esri team

ArcGIS API for JavaScript

**Comment by macandcheese** [comment]
Hi @richiecarmichael - apologies - this is actually a limitation of the documentation site component sample. Each change to a "property knob" in the Configuration panel reloads the content in the preview iFrame. 

Since the sample code has "Manufacturing" `selected` via attribute, it's being reset to that value when `disabled` is set.

Outside of that environment it should be working as intended: https://codepen.io/mac_and_cheese/pen/GRBjYOp

**Comment by richiecarmichael** [comment]
Thanks for the explanation. Verified that `calcite-select` works as expected.

**Comment by macandcheese** [comment]
@richiecarmichael  - I've added an issue in our documentation repo to look for ways to improve this down the road. 

No immediate plan to work on that, but it can understandably be a point of confusion, so it'd be nice to improve on when time allows.
