### ISSUE TITLE
Modal loses focus trap after clicking inside

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6281]
### Actual Behavior

Clicking inside a modal causes the modal's focus trap to become deactivated.

### Expected Behavior

Clicking inside a modal does not deactivate the modal's focus trap.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/JjBJYee

### Reproduction Steps

1. Visit the sample and tab around to see the focus trap is in place.
2. Click on the modal's header, its content, or on any of its buttons (slotted or otherwise).
3. Tab around and see focus now moves outside of the modal.

### Reproduction Version

next.721

### Impact

A very high adverse impact to accessibility.

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment]
Preliminary findings on this one:

* `focus-trap` is [configured to disable the trap when clicking outside](https://github.com/Esri/calcite-components/blob/master/src/utils/focusTrapComponent.ts#L50).
* By default, `clickOutsideDeactivates: true` is deactivating the trap when clicking inside the modal
* Using a custom `clickOutsideDeactivates` handler (deactivating if the click target is outside of the modal trap) helps fix this issue, but is now causing another issue where clicking on the focusable items within the modal (buttons in the example case) aren't consistently focused. **This is the main blocker at the moment.**
* [`document` is set to the trap's owner document](https://github.com/Esri/calcite-components/blob/master/src/utils/focusTrapComponent.ts#L51) instead of the component's shadow host (as [recommended in the doc](https://github.com/focus-trap/focus-trap#user-content-shadow-dom)). 
* The tab index for the fallback focus element is set to -1 [via prop](https://github.com/Esri/calcite-components/blob/master/src/utils/focusTrapComponent.ts#L45-L47) instead of attribute (as [recommended in the doc](https://github.com/focus-trap/focus-trap#your-trap-should-include-a-tabbable-element-or-a-focusable-container)). This doesn't reflect and could potentially mess up anything querying by the attribute.

At this point, it's unclear to me whether this is a limitation of `focus-trap` + shadow DOM, a bug or something we're missing in our `focus-trap` options. We'll have to dig a bit more.

**Comment by geospatialem** [comment]
Migrating to the upcoming February milestone for the fix to land later this month.

**Comment by geospatialem** [comment]
Verified in `1.0.5`

![verify-modal-focus-trap](https://user-images.githubusercontent.com/5023024/217848932-1a226f6a-4122-4ac8-8bcc-c4b5e77f126f.gif)

**Comment by jcfranco** [comment]
FYI, we'll have to reopen this one and revisit it in a future milestone. This fix introduced a bug where inputs cannot be focused (see #6454). We are reverting for a patch.

**Comment by jcfranco** [comment]
I finally managed to reproduce the issue that required us to revert previously. Need to spend some extra time digging into this one.

**Comment by geospatialem** [comment]
> I finally managed to reproduce the issue that required us to revert previously. Need to spend some extra time digging into this one.

@jcfranco Provide research findings to the April milestone, work will be carried out in a future milestone.

**Comment by driskull** [comment]
> At this point, it's unclear to me whether this is a limitation of focus-trap + shadow DOM

That's my guess. I'm guessing focus-trap and shadow DOM don't work well here.

It may just need to be acceptable for now that clicking disables the focus trap.

**Comment by jcfranco** [comment]
This was fixed via https://github.com/Esri/calcite-components/issues/6581. Testing looks great on https://github.com/Esri/calcite-components/issues/6454 too!

Thanks @driskull! 🚀

cc @anveshmekala

**Comment by driskull** [comment]
Sweeet!

**Comment by geospatialem** [comment]
Verified with `1.3.0-next.3`
![modal-verify-focus-trap-click-inside](https://user-images.githubusercontent.com/5023024/231835307-ab48801f-5313-414c-9dfe-3799eea63247.gif)
