### ISSUE TITLE
Rename `pagination` props to be descriptive

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6285]
### Description

The `pagination` components props should be renamed to be more descriptive 
cc @anveshmekala 

### Proposed naming changes
- `num` → `pageSize`
- `total` → `totalItems`
- `start` → `startItem`

### Proposed Advantages

API Consistency

### Which Component

pagination

**Comment by geospatialem** [comment]
This breaking change will be discussed for either the January, or for inclusion in a future release in the next few weeks and the milestone may change.

**Comment by jcfranco** [comment]
Since this component mainly represents pages and not item/value pairs like other components, I'm leaning towards:

* `num` → `pageSize`/`itemsPerPage` (change default to 1; breaking for REST API use cases not setting this)  
* `total` → `pages`/`totalPages` (change default to 1; breaking for REST API use cases not setting this)  
* `start` → `page`/`selectedPage` (no change to default)

WDYT?

Note: I included default changes as well, but these could be handled separately if convenient.

**Comment by anveshmekala** [comment]
I can get behind `num`→ `pageSize` .

For `total` → `pages`/`totalPages`, naming with `pages` as suffix or prefix might be contradictory here because the value is related to total number of items which will be divided with `pageSize`. Either of the suggested names sound more like total no of pages irrespective of the number of items. 

start → `page`/`selectedPage` (no change to default) This seems like a good idea and i checked with other design system which does allow user to specify which page to show up on initial rendering . This might require some change in component code as well. If we are considering only name change then user might enter a value and expect the valued page number is shown where as actual behavior shows up page in which the item index is located.

**Comment by benelan** [comment]
Based on Franco's comment it sounds like the suggestion includes changing the prop's value from total items to total pages too?

 I think logically that makes sense for a component about pages, but it may make it harder to use for everyone, not just AGOL. Currently you can use an array's length for the `total` property, which makes dynamically changing the items easier. [Here is an example](https://codepen.io/benelan/pen/bGvdEgR).

Either way, I don't think we should consider changing the `total` prop from items to pages for v1. It's a lot of surface area that would need refactoring for all of the teams using pagination with the REST API. I think it may be worth messaging stakeholders to see how big of an impact it will be for them if that's what we are thinking about.

If we aren't discussing changing from total items to total pages then I agree with Anvesh's comment about the `totalPages` prop name. Maybe something like `totalItems` instead?

**Comment by jcfranco** [comment]
@anveshmekala @benelan Ah, thanks for correcting me on `start` and `total`'s behavior. In that case, my vote is for `pageSize`/`totalItems`/`selectedItem` and no change to defaults.

**Comment by benelan** [comment]
Nice catch, yeah `start` is for items too I spaced on that one. Idk about `selectedItem` though because it's really just setting which item shows up at the top of the page. The item isn't selected in anyway so that may be confusing and conflict with our existing `selectedXYZ` naming convention. What about `startItem`/`firstItem`/`topItem`/`leadingItem` or something along those lines?

**Comment by anveshmekala** [comment]
i would vote for `startItem` or `startItemIndex` for `start` . Agree with @benelan  about using `selected` which might be confusing here as we don't select the item.

**Comment by geospatialem** [comment]
Given the discussion above, what do folks think if we pushed this issue back to a future milestone to gather feedback from key stakeholders to guide us in the renaming of the properties? cc: @jcfranco

**Comment by benelan** [comment]
> Either way, I don't think we should consider changing the total prop from items to pages for v1.

If you're referring to this, it no longer applies since we are just renaming and not changing what the prop represents

**Comment by geospatialem** [comment]
Didn't provide a lot of context to the comment above, was thinking more with the lengthy discussion and proximity to release if it would be best to hold off. Could have a high impact on teams with their upcoming releases, and they might want to weigh in on some of the changes as well. 

But if we're settled on the property renames, we can proceed as well.

**Comment by jcfranco** [comment]
> Since when did this become a democracy, have you stepped down as [benevolent dictator for life](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life)?

I'm merely giving you the illusion of a democracy. 😈 #benevolentdictator4life

Let's move forward with:

- `pageSize`
- `totalItems`
- `startItem`

Roundabout to pretty much what @anveshmekala had originally suggested. 🙃

**Comment by subgan82** [comment]
> Didn't provide a lot of context to the comment above, was thinking more with the lengthy discussion and proximity to release if it would be best to hold off. Could have a high impact on teams with their upcoming releases, and they might want to weigh in on the renames.

Thanks @geospatialem for bringing this discussion. Are we able to create team alias which includes product stakeholders using calcite can be tagged ?

**Comment by jcfranco** [comment]
@anveshmekala can correct me if I'm wrong, but I believe this would only impact `pagination`.

**Comment by anveshmekala** [comment]
Yup, it impacts `calcite-pagination` only.

**Comment by geospatialem** [comment]
Verified on `next.730` with the following:

```html
<calcite-pagination total-items="1000" page-size="10" start-item="1"></calcite-pagination>
```
