### ISSUE TITLE
[Bug] calcite-icon in calcite-button changed color from v.98 to v.99

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#6301]
### Actual Behavior

v.98: 
![image](https://user-images.githubusercontent.com/2125181/213028345-5423c1c0-d720-4720-b295-e4ea1e8414ec.png)
v.99:
![image](https://user-images.githubusercontent.com/2125181/213028419-0b63835b-98f1-44fb-a2a5-c8f1194d8f46.png)

### Expected Behavior

Continuation of v.98 and earlier coloring

### Reproduction Sample

https://codepen.io/miketschudi/pen/ZEjXMzL

### Reproduction Steps

Please see reproduction sample:  just change version from v.98 to v.99

### Reproduction Version

beta.99

### Regression?

beta.98

### Esri team

ArcGIS Solutions

**Comment by macandcheese** [comment]
Hi @MikeTschudi - `color` property was changed to `kind` in recent releases. We will be updating the documentation site alongside the release of v1.0, apologies that it is out of date. You can also use the built in `icon-start` and `icon-end` properties instead of using a button inside:

https://codepen.io/mac_and_cheese/pen/XWBePde?editors=1010

**Comment by MikeTschudi** [comment]
Splendid--thanks, @macandcheese!
