### ISSUE TITLE
placement attribute in calcite-input-date-picker doesn't work 

### ISSUE THREAD

**Issue by imdoom** [Esri/calcite-components#6370]
### Actual Behavior

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/

changing placement to "top", "top-start" or "top-end" doesn't have any effect

### Expected Behavior

The date picker should open at top when "top" is selected

<img width="1704" alt="Screenshot 2023-01-27 at 5 25 49 PM" src="https://user-images.githubusercontent.com/21358353/215234291-f72400d0-c0cd-456e-9109-abf8d82d6bd2.png">

### Reproduction Sample

https://codepen.io/akgp2707/pen/eYjKLKa

### Reproduction Steps

1. Use `calcite-Input Date Picker` as outlined in https://developers.arcgis.com/calcite-design-system/components/input-date-picker/ with the placement="top" prop.
2. Open devTools
3. See that the prop include placement="top" but the date picker doesn't open from top.

### Reproduction Version

1.0.3

### Relevant Info

Chrome: Version 109.0.5414.87 (Official Build) (x86_64)

### Regression?

1.0.0-beta.97

### Impact

Being used in Portal Home App's Notebook's create task modal.

### Esri team

ArcGIS Enterprise

**Comment by jcfranco** [comment]
I'm not seeing anything odd in particular. The date picker opens down because there's no space on top _within the sample iframe_. Could you provide a little more detail on what you're expecting to see? 

The `placement` property will be honored as long as there is available space: https://codepen.io/jcfranco/pen/NWBzOjJ?editors=1000

**Comment by jcfranco** [comment]
Closing as invalid based on ☝️. Please reopen if I missed something.
