### ISSUE TITLE
Accordion: Is it possible to have a configuration to change the heading?

### ISSUE THREAD

**Issue by FelFly** [Esri/calcite-components#645]
Request:

During the developer accessibility training, I asked the question "Is it better to have unordered headings or strong text?" and they answered headings - even if not nested properly were preferable because screen-readers having the keyboard shortcut for navigating by headings. It'd be helpful for our team if we could set what the DOM element (h2, h3, h4, h5, h6, span) via a knob on the accordion was instead of being limited to the span class `.accordion-item-title`. 

Having similar functionality like this on Notice would also be extremely beneficial because we tend to use the Notice component like an inline alert (that is not dismissible) on pages to help provide instructions on how to use functionality or explain why certain settings aren't available and the `.notice-title` would often also be used as a heading.

https://esri.github.io/calcite-components/?path=/story/accordion--simple
https://esri.github.io/calcite-components/?path=/story/notice--simple

**Comment by macandcheese** [comment]
Hi @FelFly - so, for `calcite-notice` - you can actually just use a desired heading as the slotted elements:

```
<calcite-notice color="red" active>
    <h2 slot="notice-title">Something failed</h2>
    <h3 slot="notice-message">That thing you wanted to do didn't work as expected</h3>
    <calcite-link slot="notice-link" title="my action">Retry</calcite-link>
</calcite-notice>
```

HOWEVER! Currently the styles only apply to slotted `div` - if you do this now all the styles will be wonky. So I'll update the slotted styling to override any slotted elements to keep styling consistent while letting folks use whatever they'd like. 

For accordions - we'd need to accept a prop to change that because the `item-title` and `item-subtitle` are not slotted but passed as strings. Would you want to set the heading level of both `item-title` and `item-subtitle`?

We can work on standardizing a convention for this, because I'm sure it will come up in other places where folks will want to adjust the rendered DOM element while not affecting styling for certain strings.

**Comment by FelFly** [comment]
@macandcheese I think it's more useful only at the `.item-twitter` level because if I am using a screenreader to scan through headings by keyboard shortcut, I think less is more for purposes of skimming through headings, especially if there are many on a page. For an idea of what that looks like - the more headings you add, the slower it is to get through this list for a non-sighted user.
![image](https://user-images.githubusercontent.com/7389593/83907768-f68fa080-a733-11ea-8c08-7874e8b677fc.png)
