### ISSUE TITLE
Extra share icon

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-components#6480]
### Description

There's one share icon available in the Calcite iconset. However, another icon is also commonly used in apps. 
![image](https://user-images.githubusercontent.com/25850072/218977107-f88c88b7-fb08-47b5-a355-d45c4173c309.png)

Can this icon be added to the set: https://www.flaticon.com/free-icon/share-button_61020?
![image](https://user-images.githubusercontent.com/25850072/218977166-898450ce-ba73-4b5e-a098-37dfaca87c7e.png)

### User Stories

The current icon is not clear for the end users who are familiar with phone apps where this other share icon is used

### Acceptance Criteria

The extra share icon becomes available in the Calcite iconset.

### Esri team

Esri Netherlands

**Comment by macandcheese** [comment]
Hi @arjanvanzutphen - can you access Workfront to make a request to the icon team? 

I’ll follow up on Teams, but that’s the correct venue for icon requests :)

**Comment by SkyeSeitz** [comment]
Hi @arjanvanzutphen, the Icon Team has researched this in the past and found that we were restricted from using this version of the share icon due to, I believe, a copyright. Tagging @sfrizzell @allieorth @nicklu to confirm if this is still the case before you submit an icon request through Workfront :)

**Comment by sfrizzell** [comment]
This is correct. We have not included the 3 dots connected with 2 lines depiction for "share" since that is a trademarked design owned by ShareThis (sharethis.com). The icon version of that design is commonly used/seen as a generic representation of "share" in various icon sets, but it shouldn't be. This is similar to the misuse of the American Red Cross logo to represent something medical. With the Red Cross logo, the nuances of usage get more complicated (color, container, context), but our approach has been to honor trademarked logo restrictions when we are aware of potential conflicts with icons in our libraries.

**Comment by SkyeSeitz** [comment]
Thank you for the info, @sfrizzell!

**Comment by SkyeSeitz** [comment]
Closing with the context provided from the Icon Team above.
