### ISSUE TITLE
Clicking primary modal button shifts focus out of modal before modal closes

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6579]
### Actual Behavior

Whatever element had focus when opening a modal immediately regains focus when clicking the modal's primary button -- even if clicking the primary button does not immediately close the modal.

### Expected Behavior

Whatever element had focus when opening a modal regains focus only after the modal is done closing.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/dyqVxyy

### Reproduction Steps

1. Visit the sample and click the **Open modal** button.
2. Use the mouse to click the **Save** button.
3. Notice focus has moved back to the **Open modal** button behind the modal.

### Reproduction Version

1.0.8

### Priority impact

p2 - want for current milestone

### Impact

The Field Maps web app has several modals that defer closing themselves until some asynchronous operation is finished (e.g. saving or duplicating a map). To prevent the user from triggering other operations, focus should remain trapped in the modal until it's closed.

In cases where the primary button does not immediately close the modal, this bug effectively allows keyboard navigation to prematurely escape the modal's focus trap.

### Esri team

ArcGIS Field Apps

**Comment by driskull** [comment]
I think this may be an issue with the FocusTrap and shadowDOM.

- If you try with a native button instead of a calcite-button everything works fine.
- If you click on the edge of the calcite-button (not on the text) then everything works fine.

I think that when clicking on the text portion of the calcite-button the focus-trap thinks the click is outside of the modal and therefore deactivates the focus trap.

**Comment by driskull** [comment]
Created issue for `focus-trap`. https://github.com/focus-trap/focus-trap/issues/959

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.21` with the the latest focus-trap addition.
