### ISSUE TITLE
[calcite-label] Multiple calcite-select's wrapped in a calcite-label not focusing

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-components#6644]
### Actual Behavior

When using two `calcite-select` components wrapped in a `calcite-label`, the second `calcite-select` component after selecting for drop down does not focus. Instead, the dropdown menu shows very quickly but not long enough for selection.

### Expected Behavior

The expected behavior is for multiple `calcite-select` components to have click-able dropdowns once selected when encapsulated in a `calcite-label` div.

### Reproduction Sample

https://codepen.io/jasdelreyes/pen/NWLePoY

### Reproduction Steps

1. Open the codepen
2. Click both select components to select from the dropdowns
3. See that the second dropdown not initially focused does not allow for any option to be selected
4. Un-comment the calcite-label div
5. See that the two select components correctly behave.

### Reproduction Version

1.0.7

### Priority impact

p2 - want for current milestone

### Impact

I've found a workaround but this issue directly impacts a necessary action as part of the new append experience on the item page to be released in R02, which you can test out on devext (and test out the double dropdowns in the `update` or `upsert` selection).

### Esri team

ArcGIS Online

**Comment by jasdelreyes** [comment]
Thanks! @geospatialem I do have labels assigned to each `calcite-select` component in the actual implementation of this issue in my project. I liked using the `calcite-label` component div to allow for a header and description to hug the top and bottom of the `calcite-select` components, but I don't think your example accounts for that case (having the `calcite-select` components, top text div and bottom text div all wrapped in a `calcite-label`).

**Comment by geospatialem** [comment]
@jasdelreyes Labels should only be associated with one element for folks and technologies to discern the content.

Could potentially be a better use for either a `fieldset` and `legend` instead of one `label` for both elements, such as the [Grouping form controls example](https://developers.arcgis.com/calcite-design-system/foundations/accessibility/#grouping-form-controls).

Something similar to this: https://codepen.io/geospatialem/pen/vYzvzxY

Alternatively, could house the elements under a heading for context as well.

**Comment by jasdelreyes** [comment]
Got it. Thank you so much, this makes sense! @geospatialem

**Comment by geospatialem** [comment]
@jasdelreyes Closing per our discussion above.
