### ISSUE TITLE
Alignment issues with input and other components

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#666]
This is a question or an issue.
Check this bin: https://jsbin.com/rudajaj/edit?html,css,output

The input is never aligning in a container with other components because there is a 'wrapper' in the component that adds a margin top of 4px.
![image](https://user-images.githubusercontent.com/3506166/84719952-8a7e1b00-af31-11ea-8d20-5472c3639193.png)

What's the rational?

The only way I can turn off this margin is by creating a style rule:
```
.calcite-input-wrapper {
 margin: 0;
}
```
Is it consider good practice?

/cc @bpatterson88

**Comment by macandcheese** [comment]
Yep, there's an open issue to remove that and place it on the wrapping `calcite-label` if present, so `calcite-input` can be used without that spacing: https://github.com/Esri/calcite-components/issues/480
That should be addressed in an upcoming `calcite-input/label` PR.

Overriding the CSS works in this case because `calcite-input` doesn't use shadow DOM (our only component to not do so, due to conflicts with password managers and their inserted DOM, we had to not use shadow).

We do provide a slot for positioning a button adjacent to an input (can also be used without a wrapping `calcite-label`:

https://esri.github.io/calcite-components/?path=/story/input--with-slotted-action 

```
<calcite-label>
  My great label
  <calcite-input placeholder="Placeholder text">
    <calcite-button slot="input-action">Go</calcite-button>
  </calcite-input>
</calcite-label>
```

**Comment by ffaubry** [comment]
OK I'm closing as duplicate of #480 
Thx.
