### ISSUE TITLE
Bug: calcite-fab position wrong with long panel

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#797]
### Summary

beta.33, beta.35 or beta.36
<img src=https://user-images.githubusercontent.com/44481292/89054555-dcc2a200-d30d-11ea-9cc9-aa73d04aef35.png width=200/>

If the panel has no vertical scroll bars it's fine.

### Reproduction Steps

1.

**Comment by asangma** [comment]
I believe this is an issue being caused by the recently added `height:100%` we added to Panel's `slot-container`.
We may want to revert that in @driskull calcite-app-components porting branch and on calcite-app-components.
And I'll revisit fixing the relationship between the center-row and the Table widget.

**Comment by asangma** [comment]
Leaving this open until we can fully test in MVB.

**Comment by AdelheidF** [comment]
Verified locally with 'next' release.

**Comment by asangma** [comment]
Thanks @AdelheidF!
