### ISSUE TITLE
Tooling: Enable screenshot tests

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#887]
## Summary 

Enabling screenshot tests would help catch potential visual regressions.

## Measure of Success 

Test suite runs screenshot tests on all components.

### Resources 

https://stenciljs.com/docs/screenshot-visual-diff

**Comment by eriklharper** [comment]
This just in:  I received this response from Loyal Chow of Sauce Labs.  It sounds like we won't be able to adopt Screener until they implement shadow DOM support :(

```
As for Shadow DOM support, this is necessary for the diff to work - we do a hybrid diff (screenshot and dom). Once that's in place, then Screener Runner sounds like it can provide what you need to get started.

Thanks,

Loyal
```

Sounds like they're working on it, but it is hard to tell at this point how long it might take or if it will even happen next year or not, but we'll just have to keep checking in.  We might be able to go with something like Percy just to tide us over for a while due to this news, because something is better than nothing.

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/577
