### ISSUE TITLE
Bug: calcite-input with type="time", and clearable="false"  still shows the clear button

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#892]
### Summary
calcite-input with type="time", and clearable="false"  still shows the clear button

![image](https://user-images.githubusercontent.com/11093161/90698681-34319f00-e236-11ea-8b97-46744f55b80e.png)

### Expected Behavior

There are use cases where we dont want the clear button for type="time"

### Reproduction Steps

1.

**Comment by macandcheese** [comment]
Hey @kevindoshier  - `clearable="false"` won't works since it's just a boolean, that string still gets interpreted as true. 

The issue is that inside the component we are setting `clearable` as true for certain input types - `date`, `time`, and `search`, since some (not all) browsers append a clearable `x` button to these by default. We can remove that as a default setting for `date` and `time`, since it is not consistent between browsers (Firefox does, for example), but I think for `search` it should always be left on because that seems to be consistently set in default inputs with type search across browsers. 

It can still of course be added to `date` and `time` by adding `clearable` prop should we remove it by default.

Thoughts @kevindoshier @Esri/calcite-components ?

**Comment by kevindoshier** [comment]
Yeah I think at least the time input should have a way to not be clearable, at least in our scenario we dont have the concept of null time.

**Comment by macandcheese** [comment]
OK, I think removing that as a default setting from all inputs except `type=search` should fix for that - it'll still be possible for devs to add `clearable` if desired, and as mentioned seems inconsistent across browsers for native inputs. 

I'll leave search as is since that one does seem to have that affordance on native input on all browsers.

**Comment by kevindoshier** [comment]
That sounds great to me, thank you
