### ISSUE TITLE
Enhancement: Enhance Dropdown with a default Button

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#925]
### Description
_Would be nice to start on this soon._

Update Dropdown so that maybe the placement of `calcite-dropdown-wrapper` is more flexible.

It might also be nice for Dropdown to place a button with default styles that match the CalciteInput styles but still expose button properties at the Dropdown level. The trigger slot could always be overwritten of course.

#### User Stories
Many interfaces using Calcite Components will use Dropdown with something like
`appearance=clear`
`color=dark`
Inserting a button into the trigger slot already set up like that out of the box would make users' life easier while also assisting in aligning designs.

**Comment by macandcheese** [comment]
Can we use https://github.com/Esri/calcite-components/issues/302?

I think the select component can offer certain enhancements over a dropdown - for instance because we would only accept text values for options - we can offer a filter field (we cannot do that with slotted content in dropdown items, we have no idea what could be inside).

We could separately update the calcite dropdown positioning to use Popper to allow it to be positioned up / side, that's been requested before - but I don't want to conflate that with a Calcite Select that offers just text items and a typeahead.

>It might also be nice for Dropdown to populate the trigger slot with a button and expose button properties at the Dropdown level. The trigger slot could always be overwritten of course.

What would the reason for this be vs. the current slot?

**Comment by asangma** [comment]
I'll have a look at #302.

> What would the reason for this be vs. the current slot?

Seems like we could drop a default component in there and a) make users' lives easier and b) have a suggested component in there with some default values for its props.

**Comment by asangma** [comment]
Can we use #302?

Ya...sorry. Didn't see that issue.

**Comment by macandcheese** [comment]
Hm, I guess I'm not really in favor of having a default button with pass through props for dropdown - it would immediately need to get overridden with some combination of text, icons, button style, changes etc. and at that point you may as well just use the current slot. 

We could just document a button is a normal use case? Open to thoughts @Esri/calcite-components

**Comment by julio8a** [comment]
This one still needed?
