### ISSUE TITLE
Bug: Extra 'x' button on Time Picker in Firefox

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#931]
In Firefox, there is an extra 'x' button on the Time Picker component. The smaller x in the circle should be removed. 

![image](https://user-images.githubusercontent.com/50747646/91915231-d60dae80-ec6e-11ea-81f4-382daa722c45.png)

Noticed in Map Viewer Beta, Map Properties > Time Slider Options
https://devtesting.mapsdevext.arcgis.com/apps/mapviewer/index.html?layers=77cbb84d9fdc426f9f815f1837a744ba

@jcfranco

**Comment by macandcheese** [comment]
Having trouble navigating to find that option in the MVB... but this is replicable for both `time` and `date` in the Component Storybook. Probably just needs a browser override.

**Comment by macandcheese** [comment]
Unfortunately this is really hard to track down a fix for, FF seems to have an entire stylesheet at `chrome://global/content/bindings/datetimebox.css`, the browser overrides in our CSS doesn't seem to disable the close button. We recently removed the "`clearable` by default" for date and time, until we get this solved you could leave off `clearable` to avoid placing ours there as well.

Kind of a weird one, since Firefox lets you remove the one applied to a search field just fine 😠 🤔 !

**Comment by eriklharper** [comment]
Maybe the best solution then is to not render anything special for FF.  Do other browsers have this same issue or is it just FF?

**Comment by macandcheese** [comment]
It's just Firefox. That `clearable` prop is now opt-in for `date` and `time`. Do you mean detect Firefox in the component and not render our custom clearable for those types? Firefox DOES allow you to hide that with CSS for the search input clear button, so that one is on by default (since, that's the only input type that renders a clear button by default across all browsers).

**Comment by kat10140** [comment]
hows this going @macandcheese ?

**Comment by macandcheese** [comment]
No update unfortunately, feel free to take a crack ;)

**Comment by julio8a** [comment]
@macandcheese, 

Does this one need to be reassigned?

**Comment by macandcheese** [comment]
Yes, if possible. Not sure if this will be achievable using native time input type with ff, but there is a custom time input that I think is close to being ready.

**Comment by eriklharper** [comment]
I'll address this issue as part of #407 !

**Comment by julio8a** [comment]
Thanks @eriklharper!

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/issues/407 was installed in the previous release. Closing!
