### ISSUE TITLE
1.0 Release Cleanup

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#97]
Opening individual issues per component... stay tuned...

**Comment by dasa** [comment]
Are any of these `dependencies` loaded at runtime? If not, should they be set as `devDependencies` instead so that they don't get installed when doing a npm install?

@a11y/focus-trap: ^1.0.2                       
@esri/calcite-colors: ^1.3.1                   
@esri/calcite-base: github:ArcGIS/calcite-base 
@esri/calcite-ui-icons: ^2.0.1

**Comment by paulcpederson** [comment]
Exported docs as json and then parsed them real quick so I could see them all on one page.

I then went through and made notes on what needs to be changed so we can be consistent:
Exported docs as json and then parsed them real quick so I could see them all on one page.

I then went through and made notes on what needs to be changed so we can be consistent:

### calcite-accordion

current: appearance,iconPosition,iconType,scale,selectionMode,theme
desired: appearance,iconPosition,iconType,scale,selectionMode,theme

### calcite-accordion-item

current: active,itemSubtitle,itemTitle
desired: active,itemSubtitle,itemTitle

### calcite-alert

current: active,alertQueue,alertQueueLength,autoDismiss,autoDismissDuration,color,currentAlert,icon,scale,theme
desired: active,queue,queueLength,autoDismiss,autoDismissDuration,color,currentAlert,icon,scale,theme

#### Changes
- [ ] change `alertQueue` to `queue`?

### calcite-button

current: appearance,color,disabled,floating,href,icon,iconPosition,loading,round,scale,theme,width
desired: appearance,color,disabled,floating,href,icon,iconPosition,loading,round,scale,theme,width

### calcite-card

current: loading,selectable,selected,theme
desired: loading,selectable,selected,theme

### calcite-checkbox

current: checked,disabled,indeterminate,name,size,theme,value
desired: checked,disabled,indeterminate,name,scale,theme,value

#### Changes
- [ ] change `size` to `scale`

### calcite-chip

current: icon,scale,theme,value
desired: icon,scale,theme,value

### calcite-combobox

current: active,disabled,label,placeholder,scale,theme
desired: active,disabled,label,placeholder,scale,theme

### calcite-combobox-item

current: disabled,parentItem,selected,textLabel,value
desired: disabled,parentItem,selected,textLabel,value

### calcite-date

current: locale,max,min,nextMonthLabel,noCalendarInput,prevMonthLabel,showCalendar,value,valueAsDate
desired: active,locale,max,min,nextMonthLabel,noCalendarInput,prevMonthLabel,scale,value,valueAsDate

#### Changes
- [ ] change `showCalendar` to `active`
- [ ] add `scale` prop which sizes input/calendar to match buttons/inputs

### calcite-date-day

current: active,currentMonth,day,disabled,locale,selected
desired: active,currentMonth,day,disabled,locale,selected

### calcite-date-month

current: activeDate,locale,max,min,selectedDate
desired: activeDate,locale,max,min,selectedDate

### calcite-date-month-header

current: activeDate,locale,max,min,nextMonthLabel,prevMonthLabel,selectedDate
desired: activeDate,locale,max,min,nextMonthLabel,prevMonthLabel,selectedDate

### calcite-dropdown

current: active,alignment,maxItems,scale,theme,type,width
desired: active,alignment,maxItems,scale,theme,type,width

### calcite-dropdown-group

current: groupTitle,selectionMode
desired: groupTitle,selectionMode

### calcite-dropdown-item

current: active,href,iconEnd,iconStart
desired: active,href,iconEnd,iconStart

### calcite-icon

current: icon,mirrored,scale,textLabel,theme
desired: icon,mirrored,scale,textLabel,theme

### calcite-loader 

current: inline,isActive,noPadding,text,type,value
desired: active,inline,noPadding,scale,text,type,value

#### Changes
- [ ] change `isActive` to `active`
- [ ] add `scale` prop that matches button, input etc

### calcite-modal

current: beforeClose,closeLabel,color,disableEscape,docked,firstFocus,noPadding,size,theme
desired: beforeClose,textLabelClose,color,disableEscape,docked,firstFocus,noPadding,scale,theme,width

#### Changes
- [ ] change size to `scale`, this will only update the padding of the chrome around the modal?
- [ ] add `width` prop which sets width of modal?
- [ ] change `closeLabel` to `textLabelClose`

### calcite-notice

current: active,color,dismissible,icon,scale,theme,width
desired: active,color,dismissible,icon,scale,theme,width

### calcite-pagination

current: backgroundStyle,num,start,textLabelNext,textLabelPrevious,theme,total
desired: num,start,textLabelNext,textLabelPrevious,theme,total

### Changes
- [ ] Remove `backgroundStyle` ? This seems unnecessary?

### calcite-popover

current: closeButton,disableFlip,disablePointer,flipPlacements,offsetDistance,offsetSkidding,open,placement,referenceElement,textClose,theme
desired: closeButton,disableFlip,disablePointer,flipPlacements,offsetDistance,offsetSkidding,open,placement,referenceElement,textLabelClose,theme

#### Changes
- [ ] `textClose` to `textLabelClose`

### calcite-popover-manager
 
current: selector
desired: selector

### calcite-progress

current: reversed,text,theme,type,value
desired: reversed,text,theme,type,value

### calcite-radio-group

current: name,scale,selectedItem,theme
desired: name,scale,selectedItem,theme

### calcite-radio-group-item

current: checked,value
desired: checked,value

### calcite-slider

current: disabled,labelHandles,labelTicks,max,maxLabel,maxValue,min,minLabel,minValue,pageStep,precise,snap,step,theme,ticks,value
desired: disabled,labelHandles,labelTicks,max,maxValue,min,minValue,pageStep,precise,snap,step,textLabelMin,textLabelMax,theme,ticks,value

#### Changes
- [ ] `minLabel` => `textLabelMin`
- [ ] `maxLabel` => `textLabelMax`

### calcite-split-button

current: color,disabled,dropdownIconType,dropdownLabel,loading,primaryIcon,primaryLabel,primaryText,scale,theme
desired: color,disabled,dropdownIconType,dropdownLabel,loading,primaryIcon,primaryLabel,primaryText,scale,theme

#### Changes
- [ ] `primaryLabel` to `primaryTextLabel`
- [ ] `primaryText` to `text`?
- [ ] `primaryIcon` to `icon`?

### calcite-stepper

current: icon,layout,numbered,scale,theme
desired: icon,layout,numbered,scale,theme

### calcite-stepper-item

current: active,complete,disabled,error,itemSubtitle,itemTitle
desired: active,complete,disabled,error,itemSubtitle,itemTitle

### calcite-switch

current: color,name,scale,switched,theme,value
desired: color,name,scale,switched,theme,value

### calcite-tab

current: isActive,tab
desired: active,tab

#### Changes
- [ ] change `isActive` to `active`

### calcite-tab-nav

current: storageId,syncId
desired: storageId,syncId

### calcite-tab-title 

current: isActive,tab
desired: active,tab

#### Changes
- [ ] change `isActive` to `active`

### calcite-tabs

current: layout,theme
desired: layout,theme

### calcite-tooltip

current: offsetDistance,offsetSkidding,open,placement,referenceElement,theme
desired: offsetDistance,offsetSkidding,open,placement,referenceElement,theme

### calcite-tooltip-manager

current: selector
desired: selector

### calcite-tree

current: lines,scale,selectionMode,theme
desired: lines,scale,selectionMode,theme

### calcite-tree-item

current: expanded,selected
desired: expanded,selected




---

Feel free to edit/discuss any of these changes. Mostly isActive => active, size => scale, and making sure all passed in aria-labels are `textLabelX`

**Comment by macandcheese** [comment]
Thanks for putting this together @paulcpederson ! 

All looks good, I'd add that we should probably tack on a close label prop to the close button to alert and notice close buttons as well.

**Comment by paulcpederson** [comment]
👍 updated

**Comment by paulcpederson** [comment]
# Events

Events that are "public" (ie. meant to be a dev-facing API) should all have useful, typed event details. I think we should update our conventions file to this effect. Events that are internal should not be propagated outside the component. This will prevent devs from using internal event apis in their projects and then have them break later on without warning.

Also, from a consistency point of view, we should use the same verbs/tenses/forms for event names. We should use _present tense_ to match typical DOM Events (ie. "input" , "change", "click" not "inputted", "changed", "clicked"). When there is no detail, it may be helpful to pass the element (`this.el`) as the detail? Our conventions say to pass nothing, but IMO it doesn't hurt anybody to pass the element as both target and detail. Below is an audit of all events with some notes on how they could change to be more consistent.

### calcite-accordion
-`calciteAccordionItemHasChanged`

#### Changes
- [ ] `calciteAccordionItemHasChanged` => `calciteAccordionItemChange`
- [ ] add type to event detail (`{requestedAccordionItem}`)
  - optionally we could just pass the accordion item here, rather than an object with one property

### calcite-accordion-item

-`calciteAccordionItemKeyEvent` 
-`calciteAccordionItemSelected` 
-`closeCalciteAccordionItem`
-`registerCalciteAccordionItem`

#### Changes
- [ ] `calciteAccordionItemSelected` => `calciteAccordionItemSelect`
- [ ] `closeCalciteAccordionItem` => `calciteAccordionItemClosed`
- [ ] `registerCalciteAccordionItem` => `calciteAccordionItemRegistered`
- [ ] Type event details in all events

### calcite-alert

-`calciteAlertClose`
-`calciteAlertOpen`
-`calciteAlertSync`

### Changes
- [ ] Type event details in all events

### calcite-button

### calcite-card
-`calciteCardSelected`

### Changes
- [ ] `calciteCardSelected` => `calciteCardSelect`
- [ ] `calciteCardSelected`: can probably remove the element from the detail, as that will be in `target`?
- [ ] Type event detail

### calcite-checkbox

-`calciteCheckboxChange`

#### Changes
- [ ] add boolean representing "checked" to event detail
- [ ] Type event detail

### calcite-chip

-`calciteChipDismiss`

### calcite-combobox

-`calciteComboboxChipDismiss`
-`calciteLookupChange`

### calcite-combobox-item

-`calciteComboboxItemChange`
-`calciteComboboxItemKeyEvent`

### calcite-date

-`calciteDateChange`

#### Changes
- [ ] Use generics for `calciteDateChange` event, rather than extending `EventEmitter`

### calcite-date-day

-`calciteDaySelect`

### calcite-date-month

-`calciteActiveDateChange`
-`calciteDateSelect`

#### Changes
- [ ] Use generics for events, rather than extending `EventEmitter`

### calcite-date-month-header

-`calciteActiveDateChange`

#### Changes
- [ ] Use generics for events, rather than extending `EventEmitter`

### calcite-dropdown

#### Changes
- [ ] add `calciteDropdownSelect` event when the selected item changes
- [ ] make the detail the selected item element (or it's value?)
- [ ] add type information to detail

### calcite-dropdown-group

-`calciteDropdownItemHasChanged`
-`registerCalciteDropdownGroup`

#### Changes
- [ ] `calciteDropdownItemHasChanged` => `calciteDropdownItemChange`
- [ ] `registerCalciteDropdownGroup` => `calciteDropdownGroupRegister`
- [ ] Type all event details

### calcite-dropdown-item

-`calciteDropdownItemKeyEvent`
-`calciteDropdownItemSelected`
-`closeCalciteDropdown`
-`registerCalciteDropdownItem`

#### Changes
- [ ] `calciteDropdownItemSelected` => -`calciteDropdownItemSelect`
- [ ] `closeCalciteDropdown` => `calciteDropdownClose`
- [ ] `registerCalciteDropdownItem` => -`calciteDropdownItemRegister`

### calcite-icon

### calcite-loader

### calcite-modal

-`calciteModalClose`
-`calciteModalOpen`

#### Changes
- [ ] Ensure events have typed detail

### calcite-notice

-`calciteNoticeClose`
-`calciteNoticeOpen`

#### Changes
- [ ] Ensure events have typed detail

### calcite-pagination

-`calcitePaginationUpdate`

#### Changes
- [ ] Add type to event emitter for update and create type for payload (start, num, etc)

### calcite-popover

-`calcitePopoverClose`
-`calcitePopoverOpen`

### calcite-popover-manager

### calcite-progress

### calcite-radio-group

-`calciteRadioGroupChange`

#### Changes
- [ ] Add a detail with the value of the selected radio group item

### calcite-radio-group-item

-`calciteRadioGroupItemChange`

#### Changes
- [ ] Add a detail with the value of the selected radio group item

### calcite-slider

-`calciteSliderUpdate`

#### Changes
- [ ] Add useful event detail to update event (ie, value for single select or min + max for range slider)

### calcite-split-button

-`calciteSplitButtonPrimaryClick`

### calcite-stepper

-`calciteStepperItemHasChanged`

#### Changes
- [ ] `calciteStepperItemHasChanged` => `calciteStepperItemChange`
- [ ] Type event detail (`{ position }`)

### calcite-stepper-item

-`calciteStepperItemKeyEvent`
-`calciteStepperItemSelected`
-`registerCalciteStepperItem`

#### Changes
-`calciteStepperItemSelected` => `calciteStepperItemSelect`
-`registerCalciteStepperItem` => `calciteStepperItemRegister`

### calcite-switch

-`calciteSwitchChange`
-`change`

#### Change
- [ ] Pass detail with boolean for `switched` in `calciteSwitchChange`
- [ ] Remove `change`? (Causes compiler warning)

### calcite-tab

### calcite-tab-nav

-`calciteTabChange` 

### calcite-tab-title

-`calciteTabsActivate`

### calcite-tabs

#### Changes
- [ ] should maybe doc how to listen to tab changes on the root tab element?

### calcite-tooltip

### calcite-tooltip-manager

### calcite-tree

-`calciteTreeSelect`

### calcite-tree-item

-`calciteTreeItemSelect`

**Comment by macandcheese** [comment]
Closing in favor of component-specific issues.
